import { getLmeContext } from "@/lib/lme-server";
import { calculateWeightedMaterialCostRate, type ProjectProfitAnalysis } from "@/lib/project-profit-analysis";
import { queryProfitSourceData } from "@/lib/project-profit-analysis-server";

type ProfitRecord = Record<string, unknown> & { start_date?: string | null; analysis: ProjectProfitAnalysis; contract_summary: { has_original_contract: boolean }; material_cost_summary: { material_usage_count: number } };
const sorters: Record<string, (a: ProfitRecord, b: ProfitRecord) => number> = {
  latest: (a, b) => (b.start_date ?? "").localeCompare(a.start_date ?? ""), final_supply_desc: (a, b) => Number(b.analysis.final_supply_amount_krw ?? -Infinity) - Number(a.analysis.final_supply_amount_krw ?? -Infinity), material_cost_desc: (a, b) => Number(b.analysis.expected_material_cost_krw ?? -Infinity) - Number(a.analysis.expected_material_cost_krw ?? -Infinity), margin_desc: (a, b) => Number(b.analysis.expected_material_margin_krw ?? -Infinity) - Number(a.analysis.expected_material_margin_krw ?? -Infinity), margin_asc: (a, b) => Number(a.analysis.expected_material_margin_krw ?? Infinity) - Number(b.analysis.expected_material_margin_krw ?? Infinity), cost_rate_desc: (a, b) => Number(b.analysis.material_cost_rate ?? -Infinity) - Number(a.analysis.material_cost_rate ?? -Infinity), cost_rate_asc: (a, b) => Number(a.analysis.material_cost_rate ?? Infinity) - Number(b.analysis.material_cost_rate ?? Infinity),
};
export async function GET(request: Request) {
  const { supabase, employee } = await getLmeContext(); if (!employee) return Response.json({ error: "승인된 사용자만 조회할 수 있습니다." }, { status: 403 }); const params = new URL(request.url).searchParams; const clean = (value: string) => value.replace(/[,%()]/g, "");
  let query = supabase.from("projects").select("id, project_code, project_name, client_name, site_address, salesperson, task_manager, status, process_type, start_date, end_date"); const text = params.get("query")?.trim(); if (text) query = query.or(`project_name.ilike.%${clean(text)}%,project_code.ilike.%${clean(text)}%`);
  const dbFilters = [["status", "project_status"], ["salesperson", "salesperson"], ["task_manager", "task_manager"], ["process_type", "process_type"]] as const; for (const [column, key] of dbFilters) { const value = params.get(key); if (value) query = query.eq(column, value); } const from = params.get("start_date_from"); const to = params.get("start_date_to"); if (from) query = query.gte("start_date", from); if (to) query = query.lte("start_date", to);
  const projectsResult = await query.order("start_date", { ascending: false, nullsFirst: false }).order("id", { ascending: false }).limit(500); if (projectsResult.error) return Response.json({ error: projectsResult.error.message }, { status: 500 }); const combined = await queryProfitSourceData(supabase, projectsResult.data ?? []); if (combined.error || !combined.data) return Response.json({ error: combined.error?.message }, { status: 500 });
  let records = combined.data as ProfitRecord[]; const calculation = params.get("calculation_status"); const analysis = params.get("analysis_status"); const hasContract = params.get("has_contract"); const hasCost = params.get("has_material_cost"); if (calculation) records = records.filter((row) => row.analysis.calculation_status === calculation); if (analysis) records = records.filter((row) => row.analysis.analysis_status === analysis); if (hasContract === "true" || hasContract === "false") records = records.filter((row) => row.contract_summary.has_original_contract === (hasContract === "true")); if (hasCost === "true" || hasCost === "false") records = records.filter((row) => (row.material_cost_summary.material_usage_count > 0) === (hasCost === "true")); records.sort(sorters[params.get("sort") ?? "latest"] ?? sorters.latest);
  const calculable = records.filter((row) => row.analysis.calculation_status === "calculated" || row.analysis.calculation_status === "negative_margin"); const revenue = calculable.reduce((sum, row) => sum + Number(row.analysis.final_supply_amount_krw ?? 0), 0); const cost = calculable.reduce((sum, row) => sum + Number(row.analysis.expected_material_cost_krw ?? 0), 0); const margin = calculable.reduce((sum, row) => sum + Number(row.analysis.expected_material_margin_krw ?? 0), 0);
  return Response.json({ projects: records, kpi: { calculable_project_count: calculable.length, missing_contract_count: records.filter((row) => row.analysis.calculation_status === "missing_contract").length, missing_material_cost_count: records.filter((row) => row.analysis.calculation_status === "missing_material_cost").length, final_supply_total_krw: Number.isSafeInteger(revenue) ? revenue : null, expected_material_cost_total_krw: Number.isSafeInteger(cost) ? cost : null, expected_material_margin_total_krw: Number.isSafeInteger(margin) ? margin : null, weighted_material_cost_rate: calculateWeightedMaterialCostRate(calculable.map((row) => row.analysis)), loss_project_count: calculable.filter((row) => row.analysis.analysis_status === "loss").length } });
}
