begin;

create table if not exists public.shared_comments (
  id bigint generated by default as identity primary key,
  shared_item_id uuid not null references public.shared_items(id) on delete cascade,
  author_id bigint not null references public.employees(id) on delete restrict,
  content text not null check (char_length(trim(content)) between 1 and 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists shared_comments_shared_item_id_idx on public.shared_comments(shared_item_id, created_at);
create index if not exists shared_comments_author_id_idx on public.shared_comments(author_id);
create index if not exists shared_comments_created_at_idx on public.shared_comments(created_at);

create or replace function public.can_comment_shared_item(p_shared_item_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.shared_items
    where id = p_shared_item_id and owner_id = public.sharing_current_employee_id()
  ) or exists (
    select 1 from public.shared_item_members
    where shared_item_id = p_shared_item_id and employee_id = public.sharing_current_employee_id()
  )
$$;

create or replace function public.ensure_shared_item_for_comment(p_item_id uuid)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_employee_id bigint; v_note public.personal_notes%rowtype; v_shared_item_id uuid; v_item_type text;
begin
  v_employee_id := public.sharing_current_employee_id();
  if v_employee_id is null then raise exception 'not_authorized'; end if;
  select * into v_note from public.personal_notes where id = p_item_id and user_id = auth.uid();
  if v_note.id is null then raise exception 'owner_only'; end if;
  v_item_type := case when v_note.note_type = 'todo' then 'todo' when v_note.note_type = 'reminder' then 'schedule' else 'memo' end;
  insert into public.shared_items(item_type, item_id, owner_id)
  values (v_item_type, p_item_id, v_employee_id)
  on conflict (item_id) do update set updated_at = now()
  returning id into v_shared_item_id;
  return v_shared_item_id;
end;
$$;

create or replace function public.set_shared_comments_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists set_shared_comments_updated_at on public.shared_comments;
create trigger set_shared_comments_updated_at before update on public.shared_comments
for each row execute function public.set_shared_comments_updated_at();

alter table public.shared_comments enable row level security;
create policy shared_comments_select_participant on public.shared_comments for select to authenticated
  using (public.can_comment_shared_item(shared_item_id));
create policy shared_comments_insert_participant on public.shared_comments for insert to authenticated
  with check (author_id = public.sharing_current_employee_id() and public.can_comment_shared_item(shared_item_id));
create policy shared_comments_update_author on public.shared_comments for update to authenticated
  using (author_id = public.sharing_current_employee_id() and public.can_comment_shared_item(shared_item_id))
  with check (author_id = public.sharing_current_employee_id() and public.can_comment_shared_item(shared_item_id));
create policy shared_comments_delete_author_or_owner on public.shared_comments for delete to authenticated
  using (
    author_id = public.sharing_current_employee_id()
    or exists (select 1 from public.shared_items where id = shared_item_id and owner_id = public.sharing_current_employee_id())
  );

revoke all on public.shared_comments from anon, authenticated;
grant select, insert, update, delete on public.shared_comments to authenticated;
grant usage, select on sequence public.shared_comments_id_seq to authenticated;
grant execute on function public.can_comment_shared_item(uuid), public.ensure_shared_item_for_comment(uuid) to authenticated;

notify pgrst, 'reload schema';
commit;
