-- Project -> Section -> Task compatibility migration.
-- Existing project/task columns are intentionally preserved.
-- RLS policies for projects/tasks are not present in this repository, so this
-- migration enables RLS with no project_sections policies (default deny).
-- Add matching policies only after inspecting the live projects policies.

begin;

create table if not exists public.project_sections (
  id bigint generated by default as identity primary key,
  project_id bigint not null,
  process_type text not null,
  assembly_vendor text,
  task_manager text,
  quantity integer,
  start_date date,
  end_date date,
  status text not null default 'pending',
  memo text,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint project_sections_project_id_fkey
    foreign key (project_id)
    references public.projects(id)
    on update cascade
    on delete restrict,
  constraint project_sections_id_project_id_key
    unique (id, project_id)
);

create index if not exists project_sections_project_sort_idx
  on public.project_sections (project_id, sort_order, id);

create index if not exists project_sections_project_type_idx
  on public.project_sections (project_id, process_type);

alter table public.tasks
  add column if not exists project_section_id bigint;

create index if not exists tasks_project_section_id_idx
  on public.tasks (project_section_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'tasks_project_section_project_fkey'
      and conrelid = 'public.tasks'::regclass
  ) then
    alter table public.tasks
      add constraint tasks_project_section_project_fkey
      foreign key (project_section_id, project_id)
      references public.project_sections (id, project_id)
      on update cascade
      on delete restrict
      not valid;
  end if;
end
$$;

-- Stop rather than silently leaving tasks that cannot be migrated.
do $$
begin
  if exists (
    select 1
    from public.tasks t
    left join public.projects p on p.id = t.project_id
    where p.id is null
  ) then
    raise exception 'Cannot backfill project sections: orphan tasks.project_id values exist.';
  end if;
end
$$;

-- Each legacy project receives one default section. Existing sections are kept.
insert into public.project_sections (
  project_id,
  process_type,
  assembly_vendor,
  task_manager,
  start_date,
  end_date,
  status,
  memo,
  sort_order
)
select
  p.id,
  p.process_type,
  p.assembly_vendor,
  p.task_manager,
  p.start_date,
  coalesce(p.end_date, p.completion_due_date),
  coalesce(p.status, 'pending'),
  p.memo,
  1
from public.projects p
where not exists (
  select 1
  from public.project_sections ps
  where ps.project_id = p.id
);

-- Link legacy tasks to their project's default section.
update public.tasks t
set project_section_id = ps.id
from public.project_sections ps
where t.project_id = ps.project_id
  and ps.sort_order = 1
  and t.project_section_id is null;

-- Backfill validation. Any failure rolls back this whole migration.
do $$
begin
  if exists (
    select 1
    from public.projects p
    where not exists (
      select 1
      from public.project_sections ps
      where ps.project_id = p.id
    )
  ) then
    raise exception 'Project section backfill failed: a project has no section.';
  end if;

  if exists (
    select 1
    from public.project_sections
    where sort_order = 1
    group by project_id
    having count(*) > 1
  ) then
    raise exception 'Project section backfill failed: duplicate default sections exist.';
  end if;

  if exists (
    select 1
    from public.tasks
    where project_section_id is null
  ) then
    raise exception 'Task backfill failed: project_section_id remains null.';
  end if;

  if exists (
    select 1
    from public.tasks t
    join public.project_sections ps on ps.id = t.project_section_id
    where t.project_id <> ps.project_id
  ) then
    raise exception 'Task backfill failed: project and section do not match.';
  end if;
end
$$;

alter table public.tasks
  validate constraint tasks_project_section_project_fkey;

-- No live projects/tasks policy definitions are available locally.
-- With RLS enabled and no policies, API access is denied until a reviewed
-- follow-up migration copies the projects permission model.
alter table public.project_sections enable row level security;

commit;

-- Live RLS inspection query (run manually; not part of the migration):
-- select schemaname, tablename, policyname, roles, cmd, qual, with_check
-- from pg_policies
-- where schemaname = 'public'
--   and tablename in ('projects', 'tasks', 'shipments', 'activity_logs');
