-- Process master compatibility migration.
-- Existing text-based process_type columns are intentionally preserved.

begin;

create table if not exists public.process_types (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  sort_order integer not null default 0,
  color text,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- Make a manually-created compatible table conform without deleting rows.
alter table public.process_types
  alter column sort_order set default 0,
  alter column is_active set default true,
  alter column created_at set default now(),
  alter column updated_at set default now();

do $$
begin
  if exists (
    select 1
    from public.process_types
    where code is null
       or btrim(code) = ''
       or name is null
       or btrim(name) = ''
       or sort_order is null
       or is_active is null
       or created_at is null
       or updated_at is null
  ) then
    raise exception 'process_types contains null or blank required values; constraints were not changed.';
  end if;

  if exists (
    select 1
    from public.process_types
    group by code
    having count(*) > 1
  ) then
    raise exception 'process_types contains duplicate code values; unique index was not created.';
  end if;
end
$$;

alter table public.process_types
  alter column code set not null,
  alter column name set not null,
  alter column sort_order set not null,
  alter column is_active set not null,
  alter column created_at set not null,
  alter column updated_at set not null;

create unique index if not exists process_types_code_uidx
  on public.process_types (code);

-- Seed only process codes that are already in use. Display names intentionally
-- match legacy codes because no separate business labels exist in current data.
insert into public.process_types (
  code,
  name,
  sort_order,
  color,
  is_active
)
select
  source.process_type,
  source.process_type,
  0,
  null,
  true
from (
  select distinct btrim(process_type) as process_type
  from public.task_templates
  where process_type is not null
    and btrim(process_type) <> ''

  union

  select distinct btrim(process_type) as process_type
  from public.projects
  where process_type is not null
    and btrim(process_type) <> ''
) source
on conflict (code) do nothing;

commit;
