-- Project-to-assembly-vendor N:M relation. Legacy project vendor columns remain Primary caches.
-- Rollback: deploy the legacy-cache application first, then drop the RPCs/triggers/table only
-- after confirming no relationships exist that are absent from the legacy Primary cache.

begin;

create table public.project_assembly_vendors (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on update cascade on delete cascade,
  organization_id bigint not null references public.organizations(id) on update cascade on delete restrict,
  sort_order integer not null,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_assembly_vendors_project_organization_key unique (project_id, organization_id),
  constraint project_assembly_vendors_sort_order_check check (sort_order > 0)
);

create index project_assembly_vendors_project_id_idx on public.project_assembly_vendors (project_id);
create index project_assembly_vendors_organization_id_idx on public.project_assembly_vendors (organization_id);
create index project_assembly_vendors_is_primary_idx on public.project_assembly_vendors (is_primary) where is_primary;
create unique index project_assembly_vendors_one_primary_uidx on public.project_assembly_vendors (project_id) where is_primary;

do $$
declare
  v_target bigint;
  v_inserted bigint;
  v_excluded bigint;
begin
  select count(*) into v_target
  from public.projects
  where assembly_vendor_organization_id is not null;

  insert into public.project_assembly_vendors (
    project_id, organization_id, sort_order, is_primary
  )
  select project.id, organization.id, 1, true
  from public.projects project
  join public.organizations organization
    on organization.id = project.assembly_vendor_organization_id
  where project.assembly_vendor_organization_id is not null
  on conflict (project_id, organization_id) do nothing;

  get diagnostics v_inserted = row_count;
  v_excluded := v_target - v_inserted;
  raise notice 'project_assembly_vendors migration: target=%, inserted=%, excluded=%',
    v_target, v_inserted, v_excluded;
end
$$;

create or replace function public.can_manage_projects()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.employees
    where auth_user_id = auth.uid()
      and role in ('admin', 'manager')
      and active is true
      and approval_status = 'approved'
  );
$$;

revoke all on function public.can_manage_projects() from public, anon;
grant execute on function public.can_manage_projects() to authenticated;

create or replace function public.is_approved_erp_user()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.employees
    where auth_user_id = auth.uid() and active is true and approval_status = 'approved'
  );
$$;

revoke all on function public.is_approved_erp_user() from public, anon;
grant execute on function public.is_approved_erp_user() to authenticated;

create or replace function public.sync_project_primary_vendor(p_project_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_organization_id bigint;
  v_organization_name text;
begin
  select relation.organization_id, organization.name
    into v_organization_id, v_organization_name
  from public.project_assembly_vendors relation
  join public.organizations organization on organization.id = relation.organization_id
  where relation.project_id = p_project_id
    and relation.is_primary
  order by relation.sort_order, relation.id
  limit 1;

  update public.projects
  set assembly_vendor_organization_id = v_organization_id,
      assembly_vendor = v_organization_name,
      updated_at = now()
  where id = p_project_id;
end;
$$;

revoke all on function public.sync_project_primary_vendor(bigint) from public, anon, authenticated;

drop trigger if exists projects_sync_assembly_vendor_organization on public.projects;
drop function if exists public.sync_project_assembly_vendor_organization();

create or replace function public.project_assembly_vendors_sync_primary_cache()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'DELETE' then
    perform public.sync_project_primary_vendor(old.project_id);
    return old;
  end if;

  perform public.sync_project_primary_vendor(new.project_id);
  if tg_op = 'UPDATE' and old.project_id <> new.project_id then
    perform public.sync_project_primary_vendor(old.project_id);
  end if;
  return new;
end;
$$;

create trigger project_assembly_vendors_sync_primary_cache
after insert or update or delete on public.project_assembly_vendors
for each row execute function public.project_assembly_vendors_sync_primary_cache();

alter table public.project_assembly_vendors enable row level security;
create policy project_assembly_vendors_select_approved
  on public.project_assembly_vendors for select to authenticated
  using (public.is_approved_erp_user());

grant select on table public.project_assembly_vendors to authenticated;
revoke insert, update, delete on table public.project_assembly_vendors from authenticated;
revoke all on table public.project_assembly_vendors from anon;

create or replace function public.assert_valid_assembly_vendor_ids(p_vendor_ids bigint[])
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_ids bigint[] := coalesce(p_vendor_ids, array[]::bigint[]);
begin
  if cardinality(v_ids) <> (select count(distinct id) from unnest(v_ids) id) then
    raise exception using message = '조립업체가 중복되었습니다.', errcode = '22023';
  end if;

  if cardinality(v_ids) <> (
    select count(*)
    from public.organizations organization
    join public.organization_categories category on category.id = organization.category_id
    where organization.id = any(v_ids)
      and organization.is_active is true
      and category.code = 'partner'
  ) then
    raise exception using message = '등록되지 않은 조립업체가 포함되어 있습니다.', errcode = '23503';
  end if;
end;
$$;

revoke all on function public.assert_valid_assembly_vendor_ids(bigint[]) from public, anon, authenticated;

create or replace function public.create_project_with_sections_and_vendors(
  p_project jsonb,
  p_sections jsonb,
  p_assembly_vendor_ids bigint[]
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_project_id bigint;
  v_section_id bigint;
  v_section jsonb;
  v_first_process_type text;
  v_process_type text;
begin
  if not public.can_manage_projects() then
    raise exception using message = '프로젝트 등록 권한이 없습니다.', errcode = '42501';
  end if;
  if p_project is null or jsonb_typeof(p_project) <> 'object'
     or nullif(btrim(p_project->>'project_code'), '') is null
     or nullif(btrim(p_project->>'project_name'), '') is null then
    raise exception using message = '프로젝트 필수 입력값이 올바르지 않습니다.', errcode = '22023';
  end if;
  if p_sections is null or jsonb_typeof(p_sections) <> 'array' or jsonb_array_length(p_sections) = 0 then
    raise exception using message = '공정을 최소 1개 선택해야 합니다.', errcode = '22023';
  end if;
  perform public.assert_valid_assembly_vendor_ids(p_assembly_vendor_ids);

  select btrim(value->>'process_type') into v_first_process_type
  from jsonb_array_elements(p_sections)
  order by coalesce(nullif(value->>'sort_order', '')::integer, 0), btrim(value->>'process_type') limit 1;

  insert into public.projects (
    project_code, project_name, client_name, salesperson, site_address,
    task_manager, process_type, start_date, end_date, status, memo,
    assembly_vendor, assembly_vendor_organization_id
  ) values (
    btrim(p_project->>'project_code'), btrim(p_project->>'project_name'),
    nullif(btrim(p_project->>'client_name'), ''), nullif(btrim(p_project->>'salesperson'), ''),
    nullif(btrim(p_project->>'site_address'), ''), nullif(btrim(p_project->>'task_manager'), ''),
    v_first_process_type, nullif(p_project->>'start_date', '')::date,
    nullif(p_project->>'end_date', '')::date, 'in_progress', nullif(btrim(p_project->>'memo'), ''),
    null, null
  ) returning id into v_project_id;

  insert into public.project_assembly_vendors (project_id, organization_id, sort_order, is_primary)
  select v_project_id, vendor.id, vendor.ordinality::integer, vendor.ordinality = 1
  from unnest(coalesce(p_assembly_vendor_ids, array[]::bigint[])) with ordinality vendor(id, ordinality);

  for v_section in
    select value from jsonb_array_elements(p_sections)
    order by coalesce(nullif(value->>'sort_order', '')::integer, 0), btrim(value->>'process_type')
  loop
    v_process_type := nullif(btrim(v_section->>'process_type'), '');
    if v_process_type is null or not exists (
      select 1 from public.process_types where code = v_process_type and is_active is true
    ) then
      raise exception using message = format('활성 공정을 찾을 수 없습니다: %s', coalesce(v_process_type, '')), errcode = '22023';
    end if;

    insert into public.project_sections (
      project_id, process_type, assembly_vendor, task_manager, quantity,
      start_date, end_date, status, memo, sort_order
    ) values (
      v_project_id, v_process_type, nullif(btrim(v_section->>'assembly_vendor'), ''),
      nullif(btrim(v_section->>'task_manager'), ''), nullif(v_section->>'quantity', '')::integer,
      nullif(v_section->>'start_date', '')::date, nullif(v_section->>'end_date', '')::date,
      'pending', nullif(btrim(v_section->>'memo'), ''),
      coalesce(nullif(v_section->>'sort_order', '')::integer, 0)
    ) returning id into v_section_id;

    insert into public.tasks (
      project_id, project_section_id, task_order, task_type, task_name,
      assignee, status, start_date, due_date, completed_date
    )
    select v_project_id, v_section_id, template.task_order, template.task_type,
      template.task_name, nullif(btrim(v_section->>'task_manager'), ''),
      'pending', null, null, null
    from public.task_templates template
    where template.process_type = v_process_type
    order by template.task_order, template.id;
  end loop;

  return v_project_id;
end;
$$;

create or replace function public.update_project_with_vendors(
  p_project_id bigint,
  p_project jsonb,
  p_assembly_vendor_ids bigint[]
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.can_manage_projects() then
    raise exception using message = '프로젝트 수정 권한이 없습니다.', errcode = '42501';
  end if;
  perform public.assert_valid_assembly_vendor_ids(p_assembly_vendor_ids);

  update public.projects set
    project_code = btrim(p_project->>'project_code'),
    project_name = btrim(p_project->>'project_name'),
    client_name = nullif(btrim(p_project->>'client_name'), ''),
    site_address = nullif(btrim(p_project->>'site_address'), ''),
    salesperson = nullif(btrim(p_project->>'salesperson'), ''),
    task_manager = nullif(btrim(p_project->>'task_manager'), ''),
    process_type = btrim(p_project->>'process_type'),
    start_date = nullif(p_project->>'start_date', '')::date,
    end_date = nullif(p_project->>'end_date', '')::date,
    memo = nullif(btrim(p_project->>'memo'), ''),
    updated_at = now()
  where id = p_project_id;

  if not found then
    raise exception using message = '프로젝트를 찾을 수 없습니다.', errcode = 'P0002';
  end if;

  delete from public.project_assembly_vendors where project_id = p_project_id;
  insert into public.project_assembly_vendors (project_id, organization_id, sort_order, is_primary)
  select p_project_id, vendor.id, vendor.ordinality::integer, vendor.ordinality = 1
  from unnest(coalesce(p_assembly_vendor_ids, array[]::bigint[])) with ordinality vendor(id, ordinality);
  perform public.sync_project_primary_vendor(p_project_id);
  return p_project_id;
end;
$$;

create or replace function public.create_project_with_vendors(
  p_project jsonb,
  p_assembly_vendor_ids bigint[]
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_project_id bigint;
begin
  if not public.can_manage_projects() then
    raise exception using message = '프로젝트 등록 권한이 없습니다.', errcode = '42501';
  end if;
  perform public.assert_valid_assembly_vendor_ids(p_assembly_vendor_ids);

  insert into public.projects (
    project_code, project_name, client_name, site_address, salesperson,
    task_manager, process_type, start_date, end_date, status, memo,
    assembly_vendor, assembly_vendor_organization_id
  ) values (
    btrim(p_project->>'project_code'), btrim(p_project->>'project_name'),
    nullif(btrim(p_project->>'client_name'), ''), nullif(btrim(p_project->>'site_address'), ''),
    nullif(btrim(p_project->>'salesperson'), ''), nullif(btrim(p_project->>'task_manager'), ''),
    btrim(p_project->>'process_type'), nullif(p_project->>'start_date', '')::date,
    nullif(p_project->>'end_date', '')::date, nullif(btrim(p_project->>'status'), ''),
    nullif(btrim(p_project->>'memo'), ''), null, null
  ) returning id into v_project_id;

  insert into public.project_assembly_vendors (project_id, organization_id, sort_order, is_primary)
  select v_project_id, vendor.id, vendor.ordinality::integer, vendor.ordinality = 1
  from unnest(coalesce(p_assembly_vendor_ids, array[]::bigint[])) with ordinality vendor(id, ordinality);
  return v_project_id;
end;
$$;

revoke all on function public.create_project_with_sections_and_vendors(jsonb, jsonb, bigint[]) from public, anon;
revoke all on function public.create_project_with_vendors(jsonb, bigint[]) from public, anon;
revoke all on function public.update_project_with_vendors(bigint, jsonb, bigint[]) from public, anon;
grant execute on function public.create_project_with_sections_and_vendors(jsonb, jsonb, bigint[]) to authenticated;
grant execute on function public.create_project_with_vendors(jsonb, bigint[]) to authenticated;
grant execute on function public.update_project_with_vendors(bigint, jsonb, bigint[]) to authenticated;

commit;

-- Verification after applying:
-- select count(*) as migration_target from public.projects where assembly_vendor_organization_id is not null;
-- select count(*) as migrated from public.project_assembly_vendors where is_primary;
-- select project_id, count(*) from public.project_assembly_vendors where is_primary group by project_id having count(*) > 1;
