import { getLmeContext } from "@/lib/lme-server";
import { queryProjectCosts } from "@/lib/project-costs-server";
import type { ProjectCostEntry, ProjectCostSummary } from "@/lib/project-costs";
type Row=Record<string,unknown>&{id:number;project_code:string|null;project_name:string;client_name:string|null;salesperson:string|null;task_manager:string|null;cost_summary:ProjectCostSummary};
type ExportEntry=ProjectCostEntry&{import_batch_id?:string|null};

export async function GET(request:Request){
  const {supabase,employee}=await getLmeContext(); if(!employee)return Response.json({error:"승인된 사용자만 조회할 수 있습니다."},{status:403});
  const params=new URL(request.url).searchParams; const clean=(value:string)=>value.replace(/[,%()]/g,"");
  let query=supabase.from("projects").select("id,project_code,project_name,client_name,site_address,salesperson,task_manager,status,process_type,start_date,end_date");
  const text=params.get("query")?.trim(); if(text)query=query.or(`project_name.ilike.%${clean(text)}%,project_code.ilike.%${clean(text)}%`);
  for(const [column,key] of [["status","project_status"],["salesperson","salesperson"],["task_manager","task_manager"],["process_type","process_type"]] as const){const value=params.get(key);if(value)query=query.eq(column,value);}
  const from=params.get("start_date_from"),to=params.get("start_date_to"); if(from)query=query.gte("start_date",from); if(to)query=query.lte("start_date",to);
  const result=await query.order("start_date",{ascending:false,nullsFirst:false}).limit(500); if(result.error)return Response.json({error:result.error.message},{status:500});
  const combined=await queryProjectCosts(supabase,result.data??[]); if(combined.error||!combined.data)return Response.json({error:combined.error?.message},{status:500});
  let rows=combined.data as Row[]; const has=params.get("has_cost"); if(has==="true"||has==="false")rows=rows.filter(row=>row.cost_summary.has_cost_entries===(has==="true"));
  const category=params.get("category_code"); if(category)rows=rows.filter(row=>Boolean(row.cost_summary.category_breakdown[category]));
  const safe=rows.every(row=>row.cost_summary.amounts_are_safe); const sum=(field:keyof ProjectCostSummary)=>rows.reduce((total,row)=>total+Number(row.cost_summary[field]??0),0);
  const responseBody:Record<string,unknown>={projects:rows,categories:combined.categories,kpi:{registered_project_count:rows.filter(row=>row.cost_summary.has_cost_entries).length,unregistered_project_count:rows.filter(row=>!row.cost_summary.has_cost_entries).length,total_supply_amount_krw:safe?sum("total_supply_amount_krw"):null,total_vat_amount_krw:safe?sum("total_vat_amount_krw"):null,total_amount_krw:safe?sum("total_amount_krw"):null,subcontract_supply_amount_krw:safe?sum("subcontract_supply_amount_krw"):null,transportation_supply_amount_krw:safe?sum("transportation_supply_amount_krw"):null,labor_supply_amount_krw:safe?sum("labor_supply_amount_krw"):null,installation_supply_amount_krw:safe?sum("installation_supply_amount_krw"):null,as_service_supply_amount_krw:safe?sum("as_service_supply_amount_krw"):null,other_supply_amount_krw:safe?sum("other_supply_amount_krw"):null,void_cost_count:sum("void_cost_count"),amounts_are_safe:safe}};
  if(params.get("include_entries")!=="true")return Response.json(responseBody);
  const projectIds=rows.map(row=>row.id); if(!projectIds.length)return Response.json({...responseBody,export_entries:[]});
  let entryQuery=supabase.from("project_cost_entries").select("*").in("project_id",projectIds); if(category){const categoryId=(combined.categories??[]).find(item=>item.code===category)?.id;if(!categoryId)return Response.json({...responseBody,export_entries:[]});entryQuery=entryQuery.eq("category_id",categoryId);}
  const entryResult=await entryQuery.order("cost_date",{ascending:false}).order("created_at",{ascending:false}); if(entryResult.error)return Response.json({error:entryResult.error.message},{status:500});
  const entries=(entryResult.data??[]) as ExportEntry[]; const creatorIds=[...new Set(entries.map(entry=>entry.created_by))]; const batchIds=[...new Set(entries.map(entry=>entry.import_batch_id).filter((value):value is string=>Boolean(value)))];
  const [creators,batches]=await Promise.all([creatorIds.length?supabase.from("employees").select("auth_user_id,name").in("auth_user_id",creatorIds):Promise.resolve({data:[],error:null}),batchIds.length?supabase.from("project_cost_import_batches").select("id,file_name").in("id",batchIds):Promise.resolve({data:[],error:null})]);
  if(creators.error||batches.error)return Response.json({error:creators.error?.message??batches.error?.message},{status:500});
  const projectMap=new Map(rows.map(row=>[row.id,row])); const categoryMap=new Map((combined.categories??[]).map(item=>[item.id,item])); const creatorMap=new Map((creators.data??[]).map(item=>[item.auth_user_id,item.name])); const batchMap=new Map((batches.data??[]).map(item=>[item.id,item.file_name]));
  const projectOrder=new Map(rows.map((row,index)=>[row.id,index])); entries.sort((a,b)=>(projectOrder.get(a.project_id)??0)-(projectOrder.get(b.project_id)??0)||b.cost_date.localeCompare(a.cost_date)||b.created_at.localeCompare(a.created_at));
  responseBody.export_entries=entries.map(entry=>{const project=projectMap.get(entry.project_id);const costCategory=categoryMap.get(entry.category_id);return {project_code:project?.project_code??null,project_name:project?.project_name??"프로젝트 없음",client_name:project?.client_name??null,salesperson:project?.salesperson??null,task_manager:project?.task_manager??null,category_name:costCategory?.name??"분류 없음",cost_title:entry.cost_title,cost_date:entry.cost_date,recognition_date:entry.recognition_date,vendor_name:entry.vendor_name,document_number:entry.document_number,supply_amount_krw:Number(entry.supply_amount_krw),vat_amount_krw:Number(entry.vat_amount_krw),total_amount_krw:Number(entry.total_amount_krw),payment_status:entry.payment_status,memo:entry.memo,status:entry.status,created_at:entry.created_at,created_by_name:creatorMap.get(entry.created_by)??"등록자 미상",registration_method:entry.import_batch_id?"Excel 일괄등록":"수기 등록",batch_file_name:entry.import_batch_id?batchMap.get(entry.import_batch_id)??"Batch 정보 없음":null};});
  return Response.json(responseBody);
}
