"use client";

import Link from "next/link";
import { Check, ChevronDown, ChevronUp, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { EditReferenceTaskButton } from "@/components/workspace/AddReferenceTaskButton";
import { COMMENTS_CHANGED_EVENT, PERSONAL_NOTES_CHANGED_EVENT, REFERENCE_TASKS_CHANGED_EVENT } from "@/lib/collaboration-events";
import { getReferenceTaskDueState, isReferenceTaskCompleted, type ReferenceTask } from "@/lib/reference-tasks";
import { toast } from "@/lib/toast";

const priorityLabel = { low: "낮음", normal: "보통", high: "높음" } as const;
const priorityClass = { low: "bg-slate-100 text-slate-600", normal: "bg-blue-50 text-blue-700", high: "bg-red-50 text-red-700" } as const;
const COMPLETED_REFERENCE_PAGE_SIZE = 10;
function today() { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function dueLabel(dueDate: string | null) { const state = getReferenceTaskDueState(dueDate, today()); if (state === "unspecified") return "미지정"; if (state === "today") return "오늘"; if (state === "overdue") return `지연 · ${dueDate}`; if (state === "soon") return `임박 · ${dueDate}`; return dueDate; }

export function ReferenceTaskSection({ compact = false, onOpenCountChange, onCompletedCountChange }: { compact?: boolean; onOpenCountChange?: (count: number) => void; onCompletedCountChange?: (count: number) => void }) {
  const [tasks, setTasks] = useState<ReferenceTask[]>([]);
  const [error, setError] = useState("");
  const [pendingIds, setPendingIds] = useState<Set<string>>(() => new Set());
  const [completedOpen, setCompletedOpen] = useState(false);
  const [completedLimit, setCompletedLimit] = useState(COMPLETED_REFERENCE_PAGE_SIZE);
  const [sectionOpen, setSectionOpen] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/reference-tasks", { cache: "no-store" }); const result = await response.json() as { tasks?: ReferenceTask[]; error?: string }; if (!response.ok) { setError(result.error ?? "요청받은 작업을 불러오지 못했습니다."); return; } setTasks(result.tasks ?? []); setError(""); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); for (const eventName of [REFERENCE_TASKS_CHANGED_EVENT, COMMENTS_CHANGED_EVENT, PERSONAL_NOTES_CHANGED_EVENT]) window.addEventListener(eventName, load); return () => { window.clearTimeout(timer); for (const eventName of [REFERENCE_TASKS_CHANGED_EVENT, COMMENTS_CHANGED_EVENT, PERSONAL_NOTES_CHANGED_EVENT]) window.removeEventListener(eventName, load); }; }, [load]);
  const openTasks = useMemo(() => tasks.filter((task) => !isReferenceTaskCompleted(task)).sort((a, b) => (a.dueDate ?? "9999-12-31").localeCompare(b.dueDate ?? "9999-12-31") || b.createdAt.localeCompare(a.createdAt)), [tasks]);
  const completedTasks = useMemo(() => tasks.filter(isReferenceTaskCompleted).sort((a, b) => (b.completedAt ?? b.createdAt).localeCompare(a.completedAt ?? a.createdAt)), [tasks]);
  useEffect(() => { onOpenCountChange?.(openTasks.length); }, [onOpenCountChange, openTasks.length]);
  useEffect(() => { onCompletedCountChange?.(completedTasks.length); }, [completedTasks.length, onCompletedCountChange]);
  async function toggle(task: ReferenceTask) { if (pendingIds.has(task.id)) return; const completed = task.status !== "completed"; const previous = tasks; setPendingIds((current) => new Set(current).add(task.id)); setTasks((current) => current.map((item) => item.id === task.id ? { ...item, status: completed ? "completed" : "pending", completedAt: completed ? new Date().toISOString() : null } : item)); const response = await fetch(`/api/reference-tasks/${task.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ completed }) }); if (!response.ok) { setTasks(previous); toast.error("완료 상태를 변경하지 못했습니다."); } setPendingIds((current) => { const next = new Set(current); next.delete(task.id); return next; }); }
  async function remove(task: ReferenceTask) { if (!window.confirm("이 작업을 내 할 일에서 삭제하시겠습니까?")) return; const previous = tasks; setTasks((current) => current.filter((item) => item.id !== task.id)); const response = await fetch(`/api/reference-tasks/${task.id}`, { method: "DELETE" }); if (!response.ok) { setTasks(previous); toast.error("내 할 일을 삭제하지 못했습니다."); } }
  function renderTask(task: ReferenceTask) { return <article key={task.id} className="rounded-xl border border-violet-100 bg-white p-3"><div className="flex items-start gap-2"><button type="button" disabled={pendingIds.has(task.id)} onClick={() => void toggle(task)} aria-label="완료 전환" className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded border ${task.status === "completed" ? "border-emerald-500 bg-emerald-500 text-white" : "border-slate-300"}`}>{task.status === "completed" && <Check size={13}/>}</button><div className="min-w-0 flex-1"><p className={`break-words text-sm font-semibold ${task.status === "completed" ? "text-slate-400 line-through" : "text-slate-800"}`}>{task.title}</p><div className="mt-1 flex flex-wrap gap-1"><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${priorityClass[task.priority]}`}>{priorityLabel[task.priority]}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${getReferenceTaskDueState(task.dueDate, today()) === "overdue" && task.status !== "completed" ? "bg-red-50 text-red-700" : "bg-slate-100 text-slate-600"}`}>{dueLabel(task.dueDate)}</span></div>{task.source ? <><p className="mt-2 text-xs font-medium text-slate-500">원본 · {task.source.itemTitle}</p><p className="mt-1 line-clamp-2 whitespace-pre-wrap text-xs text-slate-600">{task.source.authorName}님 · {task.source.content}</p><Link href={`/calendar?personalNote=${task.source.itemId}#comment-${task.source.commentId}`} className="mt-2 inline-block text-[11px] font-semibold text-blue-600 hover:underline">원본 댓글 보기</Link></> : <p className="mt-2 text-xs text-slate-400">삭제되었거나 접근할 수 없는 원본입니다.</p>}</div><div className="flex shrink-0"><EditReferenceTaskButton task={task} onSaved={() => void load()}/><button type="button" onClick={() => void remove(task)} aria-label="참조 작업 삭제" className="rounded-lg p-1 text-slate-400 hover:text-red-600"><Trash2 size={13}/></button></div></div></article>; }
  return <div id="reference-tasks" className="min-w-0 rounded-xl bg-violet-50 p-3">{compact ? <button type="button" onClick={() => setSectionOpen((open) => !open)} className="flex w-full items-center justify-between text-left text-sm font-bold text-violet-700"><span>요청받은 작업 <span className="text-violet-400">{openTasks.length}</span></span>{sectionOpen ? <ChevronUp size={15}/> : <ChevronDown size={15}/>}</button> : <h3 className="text-sm font-bold text-violet-700">요청받은 작업 <span className="text-violet-400">{openTasks.length}</span></h3>}{(!compact || sectionOpen) && <>{error && <p className="mt-2 rounded-lg bg-red-50 px-2 py-1.5 text-xs text-red-600">{error}</p>}<div className="mt-2 space-y-2">{openTasks.length === 0 ? <p className="py-3 text-center text-xs text-slate-400">미완료 참조 작업이 없습니다.</p> : openTasks.map(renderTask)}</div><button type="button" onClick={() => setCompletedOpen((open) => !open)} className="mt-3 flex w-full items-center justify-between rounded-lg bg-white px-3 py-2 text-xs font-semibold text-slate-600"><span>완료한 요청 {completedTasks.length}</span>{completedOpen ? <ChevronUp size={14}/> : <ChevronDown size={14}/>}</button>{completedOpen && <div className="mt-2 space-y-2">{completedTasks.slice(0, completedLimit).map(renderTask)}{completedLimit < completedTasks.length && <button type="button" onClick={() => setCompletedLimit((limit) => limit + COMPLETED_REFERENCE_PAGE_SIZE)} className="w-full rounded-lg bg-white py-2 text-xs font-semibold text-violet-700">더 보기 ({completedTasks.length - completedLimit}건)</button>}</div>}</>}</div>;
}
