import type { SupabaseClient } from "@supabase/supabase-js";import type { ExchangeRateRecord } from "./types.ts";import { ECOS_EXCHANGE_RATE } from "./providers/exchange-rate-provider.ts";
export type ExchangeConflict={referenceDate:string;existingRate:number;sourceRate:number};
export class ExchangeRateRepository{constructor(private readonly db:SupabaseClient){}
 async acquire(mode:"initial"|"incremental",userId:string|null,userName:string,triggerSource:"admin"|"cron"){const stale=new Date(Date.now()-10*60_000).toISOString();await this.db.from("exchange_rate_sync_runs").update({status:"failed",completed_at:new Date().toISOString(),stopped_reason:"stale_lock",message:"만료된 동기화 잠금"}).eq("status","running").lt("started_at",stale);const{data,error}=await this.db.from("exchange_rate_sync_runs").insert({mode,trigger_source:triggerSource,status:"running",created_by:userId,created_by_name:userName}).select("id").single();if(error?.code==="23505")return null;if(error)throw new Error(error.message);return data;}
 async latest(){const{data,error}=await this.db.from("exchange_rates").select("reference_date,rate").eq("base_currency","USD").eq("quote_currency","KRW").eq("rate_type",ECOS_EXCHANGE_RATE.rateType).order("reference_date",{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(error.message);return data??null;}
 async existing(records:ExchangeRateRecord[]){if(!records.length)return new Map<string,number>();const{data,error}=await this.db.from("exchange_rates").select("reference_date,rate").in("reference_date",records.map(r=>r.referenceDate)).eq("base_currency","USD").eq("quote_currency","KRW").eq("rate_type",ECOS_EXCHANGE_RATE.rateType);if(error)throw new Error(error.message);return new Map((data??[]).map(row=>[row.reference_date,Number(row.rate)]));}
 async insert(records:ExchangeRateRecord[]){if(!records.length)return 0;const{error}=await this.db.from("exchange_rates").insert(records.map(r=>({reference_date:r.referenceDate,base_currency:r.baseCurrency,quote_currency:r.quoteCurrency,rate:r.rate,rate_type:ECOS_EXCHANGE_RATE.rateType,source_name:r.sourceName,source_url:r.sourceUrl??null,fetched_at:r.fetchedAt})));if(error)throw new Error(error.message);return records.length;}
 async nearest(targetDate:string){const{data,error}=await this.db.from("exchange_rates").select("reference_date,rate").eq("base_currency","USD").eq("quote_currency","KRW").eq("rate_type",ECOS_EXCHANGE_RATE.rateType).lte("reference_date",targetDate).order("reference_date",{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(error.message);return data??null;}
 async status(){const[latest,run]=await Promise.all([this.latest(),this.db.from("exchange_rate_sync_runs").select("*").order("started_at",{ascending:false}).limit(1).maybeSingle()]);if(run.error)throw new Error(run.error.message);return{latestReferenceDate:latest?.reference_date??null,latestRate:latest?Number(latest.rate):null,lastRun:run.data??null,sourceName:ECOS_EXCHANGE_RATE.sourceName,sourceUrl:ECOS_EXCHANGE_RATE.sourceUrl};}
 async complete(id:string,result:ExchangeSyncResult){const{error}=await this.db.from("exchange_rate_sync_runs").update({status:result.success?"success":"failed",completed_at:new Date().toISOString(),requested_ranges:result.requestedRanges,parsed_rows:result.parsedRows,inserted_rows:result.insertedRows,skipped_rows:result.skippedRows,invalid_rows:result.invalidRows,conflict_rows:result.conflictRows,latest_source_date:result.latestSourceDate,stopped_reason:result.stoppedReason,message:result.message}).eq("id",id);if(error)throw new Error(error.message);}}
export type ExchangeSyncResult={success:boolean;mode:"initial"|"incremental";requestedRanges:number;parsedRows:number;insertedRows:number;skippedRows:number;invalidRows:number;conflictRows:ExchangeConflict[];latestSourceDate:string|null;stoppedReason:string;message:string};
