"use client";
import { RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/Button";
import { toast } from "@/lib/toast";

type SyncRun = { started_at: string; status: "running" | "success" | "failed"; inserted_rows: number; skipped_rows: number; invalid_rows: number; conflict_rows: unknown[] };
type SyncStatus = { latestReferenceDate: string | null; lastRun: SyncRun | null; sourceName: string; sourceUrl: string };

export function LmeSyncStatus({ onSynced }: { onSynced: () => Promise<void> }) {
  const [status, setStatus] = useState<SyncStatus | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const response = await fetch("/api/statistics/lme/sync", { cache: "no-store" }); const result = await response.json() as SyncStatus & { error?: string }; if (!response.ok) throw new Error(result.error ?? "동기화 상태를 불러오지 못했습니다."); setStatus(result); setError(""); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "동기화 상태를 불러오지 못했습니다."); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function sync(mode: "initial" | "incremental") { if (mode === "initial" && !window.confirm("2024-01-01부터 현재까지 순차 동기화하시겠습니까? 이미 저장된 가격은 변경하지 않습니다.")) return; setBusy(true); try { const response = await fetch("/api/statistics/lme/sync", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(mode === "initial" ? { mode, startDate: "2024-01-01" } : { mode }) }); const result = await response.json() as { message?: string; error?: string }; if (!response.ok) throw new Error(result.error ?? result.message ?? "동기화에 실패했습니다."); toast.success(result.message ?? "LME 동기화를 완료했습니다."); await Promise.all([load(), onSynced()]); } catch (syncError) { toast.error(syncError instanceof Error ? syncError.message : "동기화에 실패했습니다."); await load(); } finally { setBusy(false); } }
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-sm font-semibold">LME 자동 동기화</h2><p className="mt-1 text-xs text-slate-500">비공식 공개 HTML을 저빈도로 확인하며 기존 가격은 덮어쓰지 않습니다.</p></div><div className="flex gap-2"><Button variant="outline" disabled={busy} onClick={() => void sync("incremental")}><RefreshCw size={15}/>지금 동기화</Button><Button variant="primary" disabled={busy} onClick={() => void sync("initial")}>{busy ? "실행 중..." : "최초 이력 동기화"}</Button></div></div>{error?<p className="mt-3 text-xs text-red-600">{error}</p>:<div className="mt-3 grid gap-2 text-xs sm:grid-cols-2 xl:grid-cols-4"><p className="rounded-xl bg-slate-50 p-3">최신 시세 기준일<br/><b>{status?.latestReferenceDate ?? "데이터 없음"}</b></p><p className="rounded-xl bg-slate-50 p-3">마지막 동기화<br/><b>{status?.lastRun ? new Date(status.lastRun.started_at).toLocaleString("ko-KR") : "실행 이력 없음"}</b></p><p className="rounded-xl bg-slate-50 p-3">최근 결과<br/><b>{status?.lastRun ? `신규 ${status.lastRun.inserted_rows} / 중복 ${status.lastRun.skipped_rows} / 오류 ${status.lastRun.invalid_rows}` : "-"}</b></p><p className="rounded-xl bg-slate-50 p-3">출처<br/><a className="font-semibold text-blue-600" href={status?.sourceUrl} target="_blank" rel="noreferrer">{status?.sourceName ?? "한국비철금속협회"}</a></p></div>}</section>;
}
