"use client";
import { useState } from "react";
import { X } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { calculateDomesticLme, LME_MARKET_SOURCE_URL } from "@/lib/lme-market";
import { formatNumber } from "@/lib/lme";
import { toast } from "@/lib/toast";

export function MarketEntryDialog({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: () => Promise<void> }) {
  const [form, setForm] = useState({ referenceDate: new Date().toISOString().slice(0,10), round: "1", materialCode: "AL", lmeAlUsdPerTon: "", exchangeRateKrwPerUsd: "", sourceUrl: LME_MARKET_SOURCE_URL, memo: "" }); const [saving, setSaving] = useState(false);
  if (!open) return null; const preview = calculateDomesticLme(Number(form.lmeAlUsdPerTon) || 0, Number(form.exchangeRateKrwPerUsd) || 0);
  async function save() { setSaving(true); try { const response = await fetch("/api/statistics/lme/market", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, round: Number(form.round) }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error ?? "등록하지 못했습니다."); toast.success("Market History에 추가했습니다."); await onSaved(); onClose(); } catch (error) { toast.error(error instanceof Error ? error.message : "등록하지 못했습니다."); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/40 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-2xl rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">LME 시장 시세 등록</h2><p className="mt-1 text-xs text-slate-500">등록 후 수정하거나 삭제할 수 없습니다. 실제 기준일과 출처를 확인해주세요.</p></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={18}/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["실제 기준일","referenceDate","date"],["LME AL (USD/ton)","lmeAlUsdPerTon","number"],["환율 (KRW/USD)","exchangeRateKrwPerUsd","number"]].map(([label,key,type]) => <label key={key} className="text-xs font-semibold text-slate-600">{label}<input type={type} min={type === "number" ? "0" : undefined} step={type === "number" ? "0.01" : undefined} value={form[key as keyof typeof form]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm"/></label>)}<label className="text-xs font-semibold text-slate-600">회차<select value={form.round} onChange={(event) => setForm({ ...form, round: event.target.value })} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="1">1차 · 둘째 주 기준</option><option value="2">2차 · 마지막 주 기준</option></select></label><label className="text-xs font-semibold text-slate-600">Material<input value="AL · 알루미늄" disabled className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm"/></label><label className="text-xs font-semibold text-slate-600 sm:col-span-2">출처 URL<input type="url" value={form.sourceUrl} onChange={(event) => setForm({ ...form, sourceUrl: event.target.value })} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm"/></label><label className="text-xs font-semibold text-slate-600 sm:col-span-2">메모<textarea rows={3} value={form.memo} onChange={(event) => setForm({ ...form, memo: event.target.value })} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm"/></label></div><div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">국내환산 LME 미리보기 <b className="ml-2">{formatNumber(preview)}원/kg</b><span className="ml-2 text-xs text-slate-400">최종값은 DB에서 계산됩니다.</span></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={onClose}>닫기</Button><Button variant="primary" disabled={saving || !form.lmeAlUsdPerTon || !form.exchangeRateKrwPerUsd} onClick={() => void save()}>{saving ? "등록 중..." : "불변 이력으로 등록"}</Button></div></div></div>;
}
