"use client";
import { useState } from "react";
import { X } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { toast } from "@/lib/toast";
type ImportIssue = { rowNumber: number; reason: string };
type ImportResult = { totalRows: number; readyRows?: number; insertedRows?: number; skippedRows: number; failedRows: number; failures?: ImportIssue[]; duplicates?: ImportIssue[] };
export function MarketImportDialog({ open, onClose, onImported }: { open:boolean; onClose:()=>void; onImported:()=>Promise<void> }) { const [file,setFile]=useState<File|null>(null); const [result,setResult]=useState<ImportResult|null>(null); const [busy,setBusy]=useState(false); if(!open)return null;
  async function submit(mode:"preview"|"commit"){if(!file)return;setBusy(true);try{const body=new FormData();body.set("file",file);body.set("mode",mode);const response=await fetch("/api/statistics/lme/market/import",{method:"POST",body});const data=await response.json() as ImportResult&{error?:string};if(!response.ok)throw new Error(data.error??"가져오기에 실패했습니다.");setResult(data);if(mode==="commit"){toast.success(`${data.insertedRows??0}건을 반영했습니다.`);await onImported();}}catch(error){toast.error(error instanceof Error?error.message:"가져오기에 실패했습니다.");}finally{setBusy(false);}}
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/40 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-2xl rounded-2xl bg-white p-5 shadow-xl"><div className="flex justify-between"><div><h2 className="text-lg font-semibold">Market History CSV 가져오기</h2><p className="mt-1 text-xs text-slate-500">UTF-8 CSV를 미리보기로 검증한 후 신규 자료만 반영합니다.</p></div><button onClick={onClose}><X size={18}/></button></div><div className="mt-4 rounded-xl border border-dashed border-slate-300 p-4"><input type="file" accept=".csv,text/csv" onChange={(event)=>{setFile(event.target.files?.[0]??null);setResult(null);}} className="text-sm"/><p className="mt-2 text-xs text-slate-500">필수: reference_date, reference_month, round, material_code, lme_al_usd_per_ton, exchange_rate_krw_per_usd, source_url</p></div>{result&&<div className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-3 text-sm sm:grid-cols-4"><div>전체<br/><b>{result.totalRows}건</b></div><div>신규 등록 가능<br/><b>{result.readyRows??result.insertedRows??0}건</b></div><div>기존 데이터 중복<br/><b>{result.skippedRows}건</b></div><div>필수값·형식·가격 오류<br/><b>{result.failedRows}건</b></div>{result.duplicates?.slice(0,5).map((issue)=><p key={`duplicate-${issue.rowNumber}`} className="col-span-full text-xs text-amber-700">{issue.rowNumber}행: {issue.reason}</p>)}{result.failures?.slice(0,5).map((failure)=><p key={`${failure.rowNumber}-${failure.reason}`} className="col-span-full text-xs text-red-600">{failure.rowNumber}행: {failure.reason}</p>)}</div>}<div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={onClose}>닫기</Button><Button variant="outline" disabled={!file||busy} onClick={()=>void submit("preview")}>미리보기</Button><Button variant="primary" disabled={!file||busy||!result||result.readyRows===0} onClick={()=>void submit("commit")}>{busy?"처리 중...":"검증 후 반영"}</Button></div></div></div>;
}
