"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { MATERIAL_USAGE_GROUP_CATEGORIES, MATERIAL_USAGE_GROUP_CATEGORY_LABELS, getMaterialUsageGroupName, type MaterialUsageGroup, type MaterialUsageGroupCategory } from "@/lib/material-usage-groups";
import { toast } from "@/lib/toast";

type Props = { projectId: number | null; value: string | null; disabled?: boolean; onChange: (value: string | null) => void };

export function MaterialUsageGroupSelector({ projectId, value, disabled, onChange }: Props) {
  const [groups,setGroups]=useState<MaterialUsageGroup[]>([]); const [creating,setCreating]=useState(false); const [saving,setSaving]=useState(false);
  const [category,setCategory]=useState<MaterialUsageGroupCategory>("frame"); const [plannedDate,setPlannedDate]=useState(""); const [memo,setMemo]=useState("");
  const load=useCallback(async()=>{if(!projectId){setGroups([]);return;}const response=await fetch(`/api/statistics/lme/material-usage-groups?projectId=${projectId}`,{cache:"no-store"});const result=await response.json() as {groups?:MaterialUsageGroup[];error?:string};if(!response.ok)throw new Error(result.error);setGroups((result.groups??[]).filter(group=>group.is_active||group.id===value));},[projectId,value]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load().catch(error=>toast.error(error instanceof Error?error.message:"사용 구분을 불러오지 못했습니다.")),0);return()=>window.clearTimeout(timer);},[load]);
  const nextSequence=useMemo(()=>Math.max(0,...groups.filter(group=>group.category===category).map(group=>group.sequence))+1,[category,groups]);
  async function create(){if(!projectId||saving)return;setSaving(true);try{const response=await fetch("/api/statistics/lme/material-usage-groups",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,category,plannedDate,memo})});const result=await response.json() as {group?:MaterialUsageGroup;error?:string};if(!response.ok||!result.group)throw new Error(result.error??"사용 구분을 만들지 못했습니다.");await load();onChange(result.group.id);setCreating(false);setPlannedDate("");setMemo("");toast.success(`${result.group.name}을 만들었습니다.`);}catch(error){toast.error(error instanceof Error?error.message:"사용 구분을 만들지 못했습니다.");}finally{setSaving(false);}}
  if(!projectId)return <div><select disabled className="w-full rounded-xl border bg-slate-50 px-3 py-2 text-sm"><option>프로젝트를 먼저 선택해 주세요.</option></select></div>;
  return <div><div className="flex gap-2"><select disabled={disabled} value={value??""} onChange={event=>onChange(event.target.value||null)} className="min-w-0 flex-1 rounded-xl border bg-white px-3 py-2 text-sm"><option value="">구분 없음</option>{groups.map(group=><option key={group.id} value={group.id} disabled={!group.is_active}>{group.name}{group.is_active?"":" · Archive"}</option>)}</select><Button type="button" variant="outline" disabled={disabled} onClick={()=>setCreating(true)}><Plus size={14}/>새 구분</Button></div>
  {creating&&<div className="fixed inset-0 z-[140] flex items-center justify-center bg-slate-950/45 p-4" onMouseDown={()=>!saving&&setCreating(false)}><div className="w-full max-w-md rounded-2xl bg-white p-5" onMouseDown={event=>event.stopPropagation()}><h3 className="font-bold">새 자재 사용 구분</h3><div className="mt-4 grid gap-3"><label className="text-xs font-semibold">구분<select value={category} onChange={event=>setCategory(event.target.value as MaterialUsageGroupCategory)} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm">{MATERIAL_USAGE_GROUP_CATEGORIES.map(item=><option key={item} value={item}>{MATERIAL_USAGE_GROUP_CATEGORY_LABELS[item]}</option>)}</select></label><div className="rounded-xl bg-slate-50 p-3 text-sm"><span className="text-xs text-slate-500">자동 생성 차수</span><strong className="block">{getMaterialUsageGroupName(category,nextSequence)}</strong></div><label className="text-xs font-semibold">예정일<input type="date" value={plannedDate} onChange={event=>setPlannedDate(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"/></label><label className="text-xs font-semibold">메모<textarea rows={3} value={memo} onChange={event=>setMemo(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"/></label></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" disabled={saving} onClick={()=>setCreating(false)}>취소</Button><Button variant="primary" disabled={saving} onClick={()=>void create()}>{saving?"생성 중...":`${getMaterialUsageGroupName(category,nextSequence)} 만들기`}</Button></div></div></div>}</div>;
}
