import { MARKET_DATA_PROVIDERS, MARKET_DATA_TYPES, type ExchangeRateRecord, type MarketDataProvider, type MarketDataValidation } from "../types.ts";

export const ECOS_EXCHANGE_RATE = { statCode:"731Y001", cycle:"D", itemCode:"0000001", statName:"3.1.1.1. 주요국 통화의 대원화환율", itemName:"원/미국달러(매매기준율)", unitName:"원", rateType:"usd_krw_deal_base_rate", sourceName:"한국은행 ECOS", sourceUrl:"https://ecos.bok.or.kr/api/" } as const;
type EcosRow={STAT_CODE?:string;STAT_NAME?:string;ITEM_CODE1?:string;ITEM_NAME1?:string;UNIT_NAME?:string;TIME?:string;DATA_VALUE?:string};
type EcosResponse={StatisticSearch?:{row?:EcosRow[];list_total_count?:number};RESULT?:{CODE?:string;MESSAGE?:string}};
export class EcosApiError extends Error { readonly code:string; constructor(code:string,message:string){super(`ECOS ${code}: ${message}`);this.code=code;} }
function isoDate(value:string){if(!/^\d{8}$/.test(value))return null;const result=`${value.slice(0,4)}-${value.slice(4,6)}-${value.slice(6,8)}`;const date=new Date(`${result}T00:00:00Z`);return !Number.isNaN(date.getTime())&&date.toISOString().slice(0,10)===result?result:null;}
function decimal(value:string){const normalized=value.replace(/,/g,"").trim();if(!/^\d+(?:\.\d+)?$/.test(normalized))return null;const number=Number(normalized);return Number.isFinite(number)&&number>0?number:null;}
export function maskEcosApiKey(value:string){return value.length<=6?"***":`${value.slice(0,2)}***${value.slice(-2)}`;}
export class ExchangeRateProvider implements MarketDataProvider<ExchangeRateRecord>{
 readonly providerCode=MARKET_DATA_PROVIDERS.EXCHANGE_RATE;readonly sourceName=ECOS_EXCHANGE_RATE.sourceName;readonly dataType=MARKET_DATA_TYPES.EXCHANGE_RATE;
 private key(){const key=process.env.BOK_ECOS_API_KEY;if(!key)throw new Error("BOK_ECOS_API_KEY가 설정되지 않았습니다.");return key;}
 buildUrl(startDate:string,endDate:string){const start=startDate.replaceAll("-","");const end=endDate.replaceAll("-","");return `https://ecos.bok.or.kr/api/StatisticSearch/${encodeURIComponent(this.key())}/json/kr/1/1000/${ECOS_EXCHANGE_RATE.statCode}/${ECOS_EXCHANGE_RATE.cycle}/${start}/${end}/${ECOS_EXCHANGE_RATE.itemCode}`;}
 async fetchRange(startDate:string,endDate:string){let last:Error|null=null;for(let attempt=0;attempt<2;attempt+=1){try{const response=await fetch(this.buildUrl(startDate,endDate),{cache:"no-store",signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`ECOS HTTP ${response.status}`);return {sourceUrl:ECOS_EXCHANGE_RATE.sourceUrl,payload:await response.text()};}catch(error){last=error instanceof Error?error:new Error("ECOS 요청 실패");if(attempt===0)await new Promise(resolve=>setTimeout(resolve,500));}}throw last??new Error("ECOS 요청 실패");}
 async fetchPage(pageNumber:number):Promise<never>{void pageNumber;throw new Error("환율 Provider는 날짜 범위 요청을 사용합니다.");}
 parse(payload:string){let body:EcosResponse;try{body=JSON.parse(payload) as EcosResponse;}catch{throw new Error("ECOS JSON 응답을 해석할 수 없습니다.");}if(body.RESULT){const code=body.RESULT.CODE??"UNKNOWN";if(code==="INFO-200")return{records:[],oldestDate:"",latestDate:""};throw new EcosApiError(code,body.RESULT.MESSAGE??"ECOS 오류");}const rows=body.StatisticSearch?.row??[];const records=rows.map(row=>{if(row.STAT_CODE!==ECOS_EXCHANGE_RATE.statCode||row.STAT_NAME!==ECOS_EXCHANGE_RATE.statName||row.ITEM_CODE1!==ECOS_EXCHANGE_RATE.itemCode||row.ITEM_NAME1!==ECOS_EXCHANGE_RATE.itemName||row.UNIT_NAME!==ECOS_EXCHANGE_RATE.unitName)throw new Error("ECOS 환율 통계 메타데이터가 예상과 다릅니다.");const referenceDate=isoDate(row.TIME??"");const rate=decimal(row.DATA_VALUE??"");if(!referenceDate||rate===null)throw new Error("ECOS 환율 날짜 또는 값이 올바르지 않습니다.");return{referenceDate,baseCurrency:"USD" as const,quoteCurrency:"KRW" as const,rate,sourceName:ECOS_EXCHANGE_RATE.sourceName,sourceUrl:ECOS_EXCHANGE_RATE.sourceUrl,fetchedAt:new Date().toISOString()};});const dates=records.map(record=>record.referenceDate).sort();return{records,oldestDate:dates[0]??"",latestDate:dates.at(-1)??""};}
 validate(record:ExchangeRateRecord):MarketDataValidation{const today=new Date().toISOString().slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(record.referenceDate)&&record.referenceDate<=today&&record.baseCurrency==="USD"&&record.quoteCurrency==="KRW"&&Number.isFinite(record.rate)&&record.rate>0?{valid:true}:{valid:false,reason:"유효하지 않은 USD/KRW 환율입니다."};}
 getUniqueKey(record:ExchangeRateRecord){return `${record.referenceDate}|USD|KRW|${ECOS_EXCHANGE_RATE.rateType}`;}getComparableValue(record:ExchangeRateRecord){return Math.round(record.rate*1_000_000)/1_000_000;}
}
export const exchangeRateProvider=new ExchangeRateProvider();
