import { getLmeContext } from "@/lib/lme-server";
import { suggestContractStatus } from "@/lib/raw-material-contracts";
import { queryRawMaterialContracts } from "@/lib/raw-material-contracts-server";

function positive(value:unknown,allowZero=false){const number=typeof value==="number"?value:Number(value);return Number.isFinite(number)&&(allowZero?number>=0:number>0)?number:null;}
export async function GET(request:Request){const{supabase,employee}=await getLmeContext();if(!employee)return Response.json({error:"승인된 사용자만 조회할 수 있습니다."},{status:403});const result=await queryRawMaterialContracts(supabase,new URL(request.url).searchParams);if(result.error)return Response.json({error:result.error.message},{status:500});return Response.json({contracts:result.data});}
export async function POST(request:Request){
 const{supabase,user,employee}=await getLmeContext();if(!user||!employee||employee.role!=="admin")return Response.json({error:"관리자 권한이 필요합니다."},{status:403});
 const body=await request.json() as Record<string,unknown>;const supplierId=typeof body.supplierId==="string"?body.supplierId:"";const materialCode=typeof body.materialCode==="string"?body.materialCode.toUpperCase():"AL";const name=typeof body.contractName==="string"?body.contractName.trim():"";const year=Number(body.contractYear);const price=positive(body.contractPriceKrwPerKg);const processing=positive(body.processingCostKrwPerKg,true);const quantity=positive(body.contractQuantityTon);const start=typeof body.effectiveStartDate==="string"?body.effectiveStartDate:"";const end=typeof body.effectiveEndDate==="string"?body.effectiveEndDate:"";const memo=typeof body.memo==="string"?body.memo.trim():"";
 if(!supplierId||!name||name.length>200||!Number.isInteger(year)||year<2000||year>2200||price===null||processing===null||quantity===null||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(start)||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(end)||end<start||memo.length>2000)return Response.json({error:"계약 입력값을 확인해 주세요."},{status:400});
 const[{data:supplier},{data:material}]=await Promise.all([supabase.from("suppliers").select("id").eq("id",supplierId).eq("is_active",true).maybeSingle(),supabase.from("lme_materials").select("code").eq("code",materialCode).eq("is_active",true).maybeSingle()]);if(!supplier)return Response.json({error:"존재하지 않거나 비활성인 AL업체입니다."},{status:400});if(!material)return Response.json({error:"존재하지 않거나 비활성인 Material입니다."},{status:400});
 const status=suggestContractStatus(start,end,quantity);const{data,error}=await supabase.from("raw_material_contracts").insert({supplier_id:supplierId,material_code:materialCode,contract_name:name,contract_year:year,contract_price_krw_per_kg:price,processing_cost_krw_per_kg:processing,effective_start_date:start,effective_end_date:end,contract_quantity_ton:quantity,remaining_quantity_ton:quantity,status,memo:memo||null,created_by:user.id}).select("*").single();if(error)return Response.json({error:error.message},{status:500});
 const requests=await supabase.rpc("get_material_usage_requests_v2",{p_project_id:null});const unallocated=(requests.data??[]).filter((row:{material_code:string;status:string;unallocated_tons:number|string})=>row.material_code===materialCode&&row.status==="active"&&Number(row.unallocated_tons)>0);
 return Response.json({contract:data,unallocatedSummary:{count:unallocated.length,totalTons:unallocated.reduce((sum:number,row:{unallocated_tons:number|string})=>sum+Number(row.unallocated_tons),0),groups:unallocated.map((row:{group_name:string|null;project_id:number|null;unallocated_tons:number|string})=>({name:row.group_name??"구분 없음",projectId:row.project_id,unallocatedTons:Number(row.unallocated_tons)}))}},{status:201});
}
