import { getLmeContext } from "@/lib/lme-server";
import { buildProfitRecord } from "@/lib/project-profit-analysis-server";
import type { ProjectContractEntry } from "@/lib/project-contracts";
import type { MaterialCostRow } from "@/lib/project-profit-analysis-server";

export async function GET(_request: Request, { params }: { params: Promise<{ projectId: string }> }) {
  const { projectId: raw } = await params; const projectId = Number(raw); const { supabase, employee } = await getLmeContext(); if (!employee) return Response.json({ error: "승인된 사용자만 조회할 수 있습니다." }, { status: 403 }); if (!Number.isInteger(projectId) || projectId <= 0) return Response.json({ error: "프로젝트 ID가 올바르지 않습니다." }, { status: 400 });
  const [projectResult, contractResult, materialResult] = await Promise.all([supabase.from("projects").select("id, project_code, project_name, client_name, site_address, salesperson, task_manager, status, process_type, start_date, end_date").eq("id", projectId).maybeSingle(), supabase.from("project_contract_entries").select("*").eq("project_id", projectId).order("contract_date", { ascending: false }).order("created_at", { ascending: false }), supabase.from("project_material_usages").select("id, project_id, material_code, pricing_basis, cost_reference_date, expected_quantity_kg, applied_unit_price_krw_per_kg, expected_cost_krw, material:lme_materials(name)").eq("project_id", projectId).order("created_at", { ascending: false })]);
  if (projectResult.error || contractResult.error || materialResult.error) return Response.json({ error: projectResult.error?.message ?? contractResult.error?.message ?? materialResult.error?.message }, { status: 500 }); if (!projectResult.data) return Response.json({ error: "프로젝트를 찾을 수 없습니다." }, { status: 404 });
  const rawMaterials = materialResult.data ?? []; const materialRows = rawMaterials.map((row) => ({ id: row.id, project_id: row.project_id, material_code: row.material_code, pricing_basis: row.pricing_basis, cost_reference_date: row.cost_reference_date, expected_quantity_kg: row.expected_quantity_kg, applied_unit_price_krw_per_kg: row.applied_unit_price_krw_per_kg, expected_cost_krw: row.expected_cost_krw })) as MaterialCostRow[]; const record = buildProfitRecord(projectResult.data, (contractResult.data ?? []) as ProjectContractEntry[], materialRows);
  const totalCost = Number(record.material_cost_summary.expected_material_cost_krw ?? 0); const breakdown = rawMaterials.map((row) => { const material = Array.isArray(row.material) ? row.material[0] : row.material; return { id: row.id, material_code: row.material_code, material_name: material?.name ?? null, expected_quantity_kg: row.expected_quantity_kg, pricing_basis: row.pricing_basis, applied_unit_price_krw_per_kg: row.applied_unit_price_krw_per_kg, expected_cost_krw: row.expected_cost_krw, cost_share_rate: totalCost > 0 ? Number(row.expected_cost_krw) / totalCost * 100 : null, cost_reference_date: row.cost_reference_date }; });
  return Response.json({ project: projectResult.data, contract_summary: record.contract_summary, contract_entries: contractResult.data ?? [], material_cost_summary: record.material_cost_summary, material_breakdown: breakdown, analysis: record.analysis, calculation_basis: { revenue_source: "project_contract_entries의 confirmed 계약 이력에서 집계한 최종 공급가액", material_cost_source: "project_material_usages에 저장된 등록 당시 원가 snapshot 합계", formula: "예상 원자재 마진 = 최종 공급가액 - 예상 원자재 원가", excluded_costs: ["외주비", "노무비", "운송비", "설치비", "AS 비용", "기타 비용"] } });
}
