"use client";

import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/Button";
import { calculateExpectedCost, normalizeExpectedQuantity, type ProjectMaterialUsage } from "@/lib/project-material-cost";

type Material = { code: string; name: string };
type ContractOption = { id: string; supplier_name: string | null; contract_name: string; effective_start_date: string; effective_end_date: string; contract_price_krw_per_kg: number; processing_cost_krw_per_kg: number; remaining_quantity_ton: number; quantity_sufficient: boolean | null };
type MarketOption = { id: string; reference_date: string; round: number; domestic_lme_krw_per_kg: number };

export function MaterialUsageDialog({ projectId, projectStartDate, materials, usage, onClose, onSaved }: { projectId: number; projectStartDate: string | null; materials: Material[]; usage: ProjectMaterialUsage | null; onClose: () => void; onSaved: () => void | Promise<void> }) {
  const [materialCode, setMaterialCode] = useState(usage?.material_code ?? materials[0]?.code ?? "AL"); const [date, setDate] = useState(usage?.cost_reference_date ?? projectStartDate ?? new Date().toISOString().slice(0, 10)); const [quantity, setQuantity] = useState(String(usage?.input_quantity ?? "")); const [unit, setUnit] = useState<"kg" | "ton">(usage?.input_unit ?? "ton"); const [basis, setBasis] = useState<"contract" | "market">(usage?.pricing_basis ?? "contract"); const [contractId, setContractId] = useState(usage?.raw_material_contract_id ?? ""); const [market, setMarket] = useState<MarketOption | null>(null); const [processing, setProcessing] = useState(usage?.processing_cost_snapshot === null || usage?.processing_cost_snapshot === undefined ? "" : String(usage.processing_cost_snapshot)); const [memo, setMemo] = useState(usage?.memo ?? ""); const [contracts, setContracts] = useState<ContractOption[]>([]); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [loadingOptions, setLoadingOptions] = useState(false);
  const expectedKg = normalizeExpectedQuantity(Number(quantity) || 0, unit); const selectedContract = contracts.find((item) => item.id === contractId); const previewPrice = basis === "contract" ? Number(selectedContract?.contract_price_krw_per_kg ?? usage?.contract_price_snapshot ?? 0) : Number(market?.domestic_lme_krw_per_kg ?? usage?.domestic_lme_snapshot ?? 0) + (Number(processing) || 0); const previewCost = calculateExpectedCost(expectedKg, previewPrice);
  useEffect(() => { if (!materialCode || !date) return; let cancelled = false; const params = new URLSearchParams({ material_code: materialCode, cost_reference_date: date }); if (expectedKg > 0) params.set("expected_quantity_kg", String(expectedKg)); const endpoint = basis === "contract" ? "contract-options" : "market-options"; void fetch(`/api/statistics/cost-analysis/${endpoint}?${params}`).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "가격 근거를 불러오지 못했습니다."); if (cancelled) return; if (basis === "contract") setContracts(payload.contracts ?? []); else { setMarket(payload.market ?? null); if (!payload.calculation_available) setError(payload.reason); } }).catch((reason: unknown) => { if (!cancelled) setError(reason instanceof Error ? reason.message : "가격 근거를 불러오지 못했습니다."); }).finally(() => { if (!cancelled) setLoadingOptions(false); }); return () => { cancelled = true; }; }, [materialCode, date, basis, expectedKg]);
  const canSave = useMemo(() => Number(quantity) > 0 && date && (basis === "contract" ? Boolean(contractId) : Boolean(market?.id ?? usage?.lme_market_price_id) && Number(processing) >= 0), [quantity, date, basis, contractId, market, usage, processing]);
  async function save() { setSaving(true); setError(null); try { const response = await fetch(usage ? `/api/statistics/cost-analysis/material-usages/${usage.id}` : "/api/statistics/cost-analysis/material-usages", { method: usage ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId, materialCode, inputQuantity: Number(quantity), inputUnit: unit, costReferenceDate: date, pricingBasis: basis, rawMaterialContractId: basis === "contract" ? contractId : null, lmeMarketPriceId: basis === "market" ? market?.id ?? usage?.lme_market_price_id : null, processingCost: basis === "market" ? Number(processing) : null, memo }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "저장하지 못했습니다."); await onSaved(); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "저장하지 못했습니다."); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4" role="dialog" aria-modal="true"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">{usage ? "예상 원자재 수정" : "예상 원자재 추가"}</h2><p className="mt-1 text-xs text-slate-500">적용단가와 예상 원가는 서버에서 다시 계산됩니다.</p></div><Button variant="ghost" onClick={onClose}>닫기</Button></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Material<select disabled={Boolean(usage)} value={materialCode} onChange={(event) => { setMaterialCode(event.target.value); setContractId(""); }} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm">{materials.map((item) => <option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">원가 기준일<input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs font-semibold text-slate-600">예상 사용량<input type="number" min="0.001" step="0.001" value={quantity} onChange={(event) => setQuantity(event.target.value)} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs font-semibold text-slate-600">입력 단위<select value={unit} onChange={(event) => setUnit(event.target.value as "kg" | "ton")} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm"><option value="kg">kg</option><option value="ton">ton</option></select></label></div>
    <div className="mt-4"><p className="text-xs font-semibold text-slate-600">가격 기준</p><div className="mt-1 flex gap-2"><Button variant={basis === "contract" ? "primary" : "outline"} onClick={() => setBasis("contract")}>계약</Button><Button variant={basis === "market" ? "primary" : "outline"} onClick={() => setBasis("market")}>시장</Button></div></div>
    {basis === "contract" ? <div className="mt-4"><h3 className="text-sm font-semibold">추천 계약</h3><div className="mt-2 space-y-2">{contracts.map((item) => <label key={item.id} className={`block cursor-pointer rounded-xl border p-3 text-xs ${contractId === item.id ? "border-blue-500 bg-blue-50" : "border-slate-200"}`}><input type="radio" name="contract" checked={contractId === item.id} onChange={() => setContractId(item.id)} className="mr-2"/><b>{item.supplier_name ?? "AL업체 미상"} · {item.contract_name}</b><span className="mt-1 block text-slate-500">{item.effective_start_date} ~ {item.effective_end_date} · {Number(item.contract_price_krw_per_kg).toLocaleString("ko-KR")}원/kg · 잔여 {Number(item.remaining_quantity_ton).toLocaleString("ko-KR")}ton · 가공비 참고 {Number(item.processing_cost_krw_per_kg).toLocaleString("ko-KR")}원</span>{item.quantity_sufficient !== null && <span className={item.quantity_sufficient ? "text-emerald-600" : "text-amber-600"}>{item.quantity_sufficient ? "예상 사용량 충족" : "예상 사용량보다 잔여수량 부족"}</span>}</label>)}{!loadingOptions && contracts.length === 0 && <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">조건에 맞는 활성 계약이 없습니다.</p>}</div></div> : <div className="mt-4 rounded-xl border border-slate-200 p-4"><h3 className="text-sm font-semibold">기준일 이하 최신 Market Price</h3>{market ? <p className="mt-2 text-sm">{market.reference_date} · {market.round}차 · 국내환산 LME {Number(market.domestic_lme_krw_per_kg).toLocaleString("ko-KR")}원/kg</p> : <p className="mt-2 text-sm text-slate-500">사용 가능한 시세가 없습니다.</p>}<label className="mt-3 block text-xs font-semibold text-slate-600">가공비 직접 입력 (원/kg)<input type="number" min="0" step="0.01" value={processing} onChange={(event) => setProcessing(event.target.value)} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label></div>}
    <label className="mt-4 block text-xs font-semibold text-slate-600">메모<textarea maxLength={2000} value={memo} onChange={(event) => setMemo(event.target.value)} className="mt-1 min-h-20 w-full rounded-lg border p-3 text-sm" /></label><div className="mt-4 rounded-xl bg-slate-950 p-4 text-white"><p className="text-xs text-slate-300">미리보기</p><div className="mt-2 grid gap-2 sm:grid-cols-3"><span>{expectedKg.toLocaleString("ko-KR")} kg</span><span>{previewPrice.toLocaleString("ko-KR")} 원/kg</span><b>{previewCost.toLocaleString("ko-KR")} 원</b></div></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={onClose}>취소</Button><Button variant="primary" disabled={!canSave || saving || loadingOptions} onClick={() => void save()}>{saving ? "저장 중" : "저장"}</Button></div></div></div>;
}
