export type PaymentStatus = "unpaid" | "partial" | "paid" | "not_applicable";
export type ProjectCostCategory = { id: string; code: string; name: string; description: string | null; sort_order: number; is_active: boolean; is_system: boolean; created_at: string; updated_at: string };
export type ProjectCostEntry = { id: string; project_id: number; category_id: string; cost_title: string; cost_date: string; recognition_date: string | null; vendor_name: string | null; document_number: string | null; supply_amount_krw: number; vat_amount_krw: number; total_amount_krw: number; status: "confirmed" | "void"; payment_status: PaymentStatus; memo: string | null; created_by: string; created_at: string; updated_at: string };
export type CategoryCostBreakdown = { category_id: string; code: string; name: string; is_active: boolean; count: number; supply_amount_krw: number; vat_amount_krw: number; total_amount_krw: number; share_rate: number | null };
export type ProjectCostSummary = { confirmed_cost_count: number; void_cost_count: number; total_supply_amount_krw: number; total_vat_amount_krw: number; total_amount_krw: number; subcontract_supply_amount_krw: number; transportation_supply_amount_krw: number; labor_supply_amount_krw: number; installation_supply_amount_krw: number; as_service_supply_amount_krw: number; other_supply_amount_krw: number; category_breakdown: Record<string, CategoryCostBreakdown>; latest_confirmed_cost_date: string | null; has_cost_entries: boolean; amounts_are_safe: boolean };
export const PAYMENT_STATUS_LABEL: Record<PaymentStatus, string> = { unpaid: "미지급", partial: "일부 지급", paid: "지급 완료", not_applicable: "해당 없음" };
export function calculateCostVat(supply: number) { return Math.round(supply * 0.1); }

export function summarizeProjectCosts(entries: ProjectCostEntry[], categories: ProjectCostCategory[]): ProjectCostSummary {
  const categoryMap = new Map(categories.map((category) => [category.id, category])); const confirmed = entries.filter((entry) => entry.status === "confirmed"); let safe = true; const breakdown: Record<string, CategoryCostBreakdown> = {};
  for (const entry of confirmed) { const category = categoryMap.get(entry.category_id); if (!category) continue; const supply = Number(entry.supply_amount_krw); const vat = Number(entry.vat_amount_krw); const total = Number(entry.total_amount_krw); if (![supply, vat, total].every(Number.isSafeInteger)) safe = false; const current = breakdown[category.code] ?? { category_id: category.id, code: category.code, name: category.name, is_active: category.is_active, count: 0, supply_amount_krw: 0, vat_amount_krw: 0, total_amount_krw: 0, share_rate: null }; current.count++; current.supply_amount_krw += supply; current.vat_amount_krw += vat; current.total_amount_krw += total; if (![current.supply_amount_krw, current.vat_amount_krw, current.total_amount_krw].every(Number.isSafeInteger)) safe = false; breakdown[category.code] = current; }
  const totalSupply = Object.values(breakdown).reduce((sum, item) => sum + item.supply_amount_krw, 0); const totalVat = Object.values(breakdown).reduce((sum, item) => sum + item.vat_amount_krw, 0); const total = Object.values(breakdown).reduce((sum, item) => sum + item.total_amount_krw, 0); if (![totalSupply, totalVat, total].every(Number.isSafeInteger)) safe = false; for (const item of Object.values(breakdown)) item.share_rate = totalSupply > 0 ? item.supply_amount_krw / totalSupply * 100 : null;
  const amount = (code: string) => breakdown[code]?.supply_amount_krw ?? 0; return { confirmed_cost_count: confirmed.length, void_cost_count: entries.length - confirmed.length, total_supply_amount_krw: totalSupply, total_vat_amount_krw: totalVat, total_amount_krw: total, subcontract_supply_amount_krw: amount("subcontract"), transportation_supply_amount_krw: amount("transportation"), labor_supply_amount_krw: amount("labor"), installation_supply_amount_krw: amount("installation"), as_service_supply_amount_krw: amount("as_service"), other_supply_amount_krw: amount("other"), category_breakdown: breakdown, latest_confirmed_cost_date: confirmed.map((entry) => entry.cost_date).sort().at(-1) ?? null, has_cost_entries: confirmed.length > 0, amounts_are_safe: safe };
}
