"use client";

import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { calculateVat, type ProjectContractEntry, type ProjectContractEntryType } from "@/lib/project-contracts";

export function ProjectContractEntryDialog({ projectId, hasOriginal, entry, onClose, onSaved }: { projectId: number; hasOriginal: boolean; entry: ProjectContractEntry | null; onClose: () => void; onSaved: () => void | Promise<void> }) {
  const [type, setType] = useState<ProjectContractEntryType>(entry?.entry_type ?? (hasOriginal ? "increase" : "original")); const [title, setTitle] = useState(entry?.contract_title ?? ""); const [contractDate, setContractDate] = useState(entry?.contract_date ?? new Date().toISOString().slice(0, 10)); const [effectiveDate, setEffectiveDate] = useState(entry?.effective_date ?? new Date().toISOString().slice(0, 10)); const [documentNumber, setDocumentNumber] = useState(entry?.document_number ?? ""); const [supply, setSupply] = useState(entry ? String(entry.supply_amount_krw) : ""); const [vat, setVat] = useState(entry ? String(entry.vat_amount_krw) : "0"); const [vatManual, setVatManual] = useState(Boolean(entry)); const [memo, setMemo] = useState(entry?.memo ?? ""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const total = (Number(supply) || 0) + (Number(vat) || 0); const isEdit = Boolean(entry);
  function changeSupply(value: string) { setSupply(value); if (!vatManual) setVat(String(calculateVat(Number(value) || 0))); }
  async function save() { setSaving(true); setError(null); try { const response = await fetch(isEdit ? `/api/statistics/project-contracts/entries/${entry?.id}` : "/api/statistics/project-contracts/entries", { method: isEdit ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(isEdit ? { contract_title: title, effective_date: effectiveDate, document_number: documentNumber, memo, status: entry?.status } : { project_id: projectId, entry_type: type, contract_title: title, contract_date: contractDate, effective_date: effectiveDate, document_number: documentNumber, supply_amount_krw: Number(supply), vat_amount_krw: Number(vat), memo }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "저장하지 못했습니다."); await onSaved(); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "저장하지 못했습니다."); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4" role="dialog" aria-modal="true"><section className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">{isEdit ? "계약 운영정보 수정" : "계약 이력 등록"}</h2><p className="mt-1 text-xs text-slate-500">공급가액은 부가세를 제외한 계약금액입니다.</p></div><Button variant="ghost" onClick={onClose}>닫기</Button></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">계약 유형<select disabled={isEdit} value={type} onChange={(event) => setType(event.target.value as ProjectContractEntryType)} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm">{!hasOriginal && <option value="original">최초 계약</option>}{hasOriginal && <><option value="increase">증액</option><option value="decrease">감액</option></>}</select></label><label className="text-xs font-semibold text-slate-600">계약 제목<input value={title} maxLength={200} onChange={(event) => setTitle(event.target.value)} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-600">계약일<input disabled={isEdit} type="date" value={contractDate} onChange={(event) => setContractDate(event.target.value)} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-600">적용일<input type="date" value={effectiveDate} onChange={(event) => setEffectiveDate(event.target.value)} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-600 sm:col-span-2">문서번호<input value={documentNumber} maxLength={100} onChange={(event) => setDocumentNumber(event.target.value)} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm"/></label></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">공급가액<input disabled={isEdit} type="number" min="0" step="1" value={supply} onChange={(event) => changeSupply(event.target.value)} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-600">부가세<div className="mt-1 flex gap-2"><input disabled={isEdit} type="number" min="0" step="1" value={vat} onChange={(event) => { setVat(event.target.value); setVatManual(true); }} className="h-9 min-w-0 flex-1 rounded-lg border px-3 text-sm"/><Button disabled={isEdit} size="sm" variant="outline" onClick={() => { setVat(String(calculateVat(Number(supply) || 0))); setVatManual(false); }}>10% 자동</Button></div></label></div><div className="mt-3 rounded-xl bg-slate-950 p-4 text-white"><p className="text-xs text-slate-300">계약 합계금액</p><p className="mt-1 text-xl font-bold">{total.toLocaleString("ko-KR")}원</p></div><label className="mt-4 block text-xs font-semibold text-slate-600">비고<textarea value={memo} maxLength={2000} onChange={(event) => setMemo(event.target.value)} className="mt-1 min-h-20 w-full rounded-lg border p-3 text-sm"/></label>{isEdit && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">핵심 금액·계약 유형·계약일은 변경할 수 없습니다. 변경이 필요하면 기존 이력을 무효 처리하고 새로 등록하세요.</p>}{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={onClose}>취소</Button><Button variant="primary" disabled={saving || !title || !contractDate || !effectiveDate || (!isEdit && (!Number.isSafeInteger(Number(supply)) || Number(supply) < 0 || !Number.isSafeInteger(Number(vat)) || Number(vat) < 0))} onClick={() => void save()}>{saving ? "저장 중" : "저장"}</Button></div></section></div>;
}
