-- Structural and data-preservation verification; run after the migration.
select table_name,column_name,data_type,is_nullable from information_schema.columns where table_schema='public' and table_name like 'glass_cost_%' order by table_name,ordinal_position;
select conrelid::regclass table_name,conname,pg_get_constraintdef(oid) from pg_constraint where conrelid in('public.glass_cost_statements'::regclass,'public.glass_cost_allocations'::regclass,'public.glass_cost_allocation_history'::regclass) order by 1,2;
select tablename,indexname,indexdef from pg_indexes where schemaname='public' and tablename like 'glass_cost_%' order by 1,2;
select tablename,policyname,cmd from pg_policies where schemaname='public' and tablename like 'glass_cost_%' order by 1,2;
select proname,pg_get_function_identity_arguments(oid) from pg_proc where pronamespace='public'::regnamespace and proname like '%glass_cost%' order by 1;
select tablename from pg_publication_tables where pubname='supabase_realtime' and tablename in('glass_cost_statements','glass_cost_allocations');
select conname,pg_get_constraintdef(oid) from pg_constraint where conrelid='public.editing_locks'::regclass and conname='editing_locks_resource_type_check';
select 'projects' table_name,count(*) row_count from public.projects union all select 'project_cost_entries',count(*) from public.project_cost_entries union all select 'project_material_usages',count(*) from public.project_material_usages union all select 'raw_material_contracts',count(*) from public.raw_material_contracts union all select 'material_usage_requests',count(*) from public.material_usage_requests union all select 'material_contract_allocations',count(*) from public.material_contract_allocations union all select 'organizations',count(*) from public.organizations union all select 'suppliers',count(*) from public.suppliers;
select s.id,s.supply_amount_krw,coalesce(sum(a.allocated_supply_amount_krw)filter(where a.status='active'),0) allocated,s.supply_amount_krw-coalesce(sum(a.allocated_supply_amount_krw)filter(where a.status='active'),0) unallocated from public.glass_cost_statements s left join public.glass_cost_allocations a on a.statement_id=s.id where s.status='active' group by s.id;
