-- Organization master: category (headquarters/partner) -> organization -> employee.
-- Existing employees.department and project text fields remain for compatibility.

begin;

create table if not exists public.organization_categories (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.organization_categories(id) on delete restrict,
  name text not null,
  function_code text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists organizations_category_normalized_name_uidx
  on public.organizations (category_id, lower(btrim(name)));

alter table public.employees
  add column if not exists organization_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'employees_organization_id_fkey'
      and conrelid = 'public.employees'::regclass
  ) then
    alter table public.employees
      add constraint employees_organization_id_fkey
      foreign key (organization_id)
      references public.organizations(id)
      on update cascade
      on delete restrict;
  end if;
end
$$;

create index if not exists employees_organization_id_idx
  on public.employees (organization_id);

insert into public.organization_categories (code, name, sort_order, is_active)
values ('headquarters', '본사', 1, true), ('partner', '협력업체', 2, true)
on conflict (code) do update
set name = excluded.name, sort_order = excluded.sort_order, is_active = true, updated_at = now();

-- Initial internal master. UI never hardcodes these names and future changes are DB-only.
insert into public.organizations (category_id, name, function_code, sort_order, is_active)
select category.id, source.name, source.function_code, source.sort_order, true
from public.organization_categories category
cross join (values
  ('공무', 'operations', 1),
  ('영업', 'sales', 2),
  ('관리', 'management', 3),
  ('임원', 'executive', 4)
) as source(name, function_code, sort_order)
where category.code = 'headquarters'
  and not exists (
    select 1 from public.organizations organization
    where organization.category_id = category.id
      and lower(btrim(organization.name)) = lower(source.name)
  );

-- Preserve historical project vendors as partner organizations.
insert into public.organizations (category_id, name, function_code, sort_order, is_active)
select category.id, source.name, 'partner', 100, true
from public.organization_categories category
cross join (
  select min(btrim(assembly_vendor)) as name
  from public.projects
  where assembly_vendor is not null and btrim(assembly_vendor) <> ''
  group by lower(btrim(assembly_vendor))
) source
where category.code = 'partner'
  and not exists (
    select 1 from public.organizations organization
    where organization.category_id = category.id
      and lower(btrim(organization.name)) = lower(source.name)
  );

-- Preserve legacy external organization values stored in employees.department.
insert into public.organizations (category_id, name, function_code, sort_order, is_active)
select category.id, source.name, 'partner', 100, true
from public.organization_categories category
cross join (
  select min(btrim(department)) as name
  from public.employees
  where department is not null and btrim(department) <> ''
    and btrim(department) not in (
      '공무', '공무부', '공무팀', '영업', '영업부', '영업팀',
      '관리', '관리부', '관리팀', '관리자', '임원'
    )
  group by lower(btrim(department))
) source
where category.code = 'partner'
  and not exists (
    select 1 from public.organizations organization
    where organization.category_id = category.id
      and lower(btrim(organization.name)) = lower(source.name)
  );

-- Link legacy employees without changing their compatibility department text.
update public.employees employee
set organization_id = organization.id
from public.organizations organization
join public.organization_categories category on category.id = organization.category_id
where employee.organization_id is null
  and (
    (organization.function_code = 'sales' and btrim(employee.department) in ('영업', '영업부', '영업팀'))
    or (organization.function_code = 'operations' and btrim(employee.department) in ('공무', '공무부', '공무팀'))
    or (organization.function_code = 'management' and btrim(employee.department) in ('관리', '관리부', '관리팀', '관리자'))
    or (organization.function_code = 'executive' and btrim(employee.department) = '임원')
    or (category.code = 'partner' and lower(btrim(employee.department)) = lower(btrim(organization.name)))
  );

alter table public.organization_categories enable row level security;
alter table public.organizations enable row level security;

create policy organization_categories_select_authenticated
  on public.organization_categories for select to authenticated using (true);
create policy organizations_select_authenticated
  on public.organizations for select to authenticated using (true);

revoke all on table public.organization_categories, public.organizations from anon;
grant select on table public.organization_categories, public.organizations to authenticated;

commit;
