import XLSX from "xlsx-js-style";
import { PAYMENT_STATUS_LABEL, type PaymentStatus } from "../project-costs.ts";

export type ProjectCostExportRow={project_code:string|null;project_name:string;client_name:string|null;salesperson:string|null;task_manager:string|null;category_name:string;cost_title:string;cost_date:string;recognition_date:string|null;vendor_name:string|null;document_number:string|null;supply_amount_krw:number;vat_amount_krw:number;total_amount_krw:number;payment_status:PaymentStatus;memo:string|null;status:"confirmed"|"void";created_at:string;created_by_name:string;registration_method:"수기 등록"|"Excel 일괄등록";batch_file_name:string|null};
export type ProjectCostExportOptions={rows:ProjectCostExportRow[];filterSummary:string;generatedAt:Date};
type Sheet=XLSX.WorkSheet&{"!freeze"?:{xSplit:number;ySplit:number}};
const HEADERS=["순번","프로젝트 코드","프로젝트명","발주처","영업담당자","업무담당자","비용 분류","비용 제목","비용 발생일","비용 귀속일","거래처/업체명","문서번호","공급가액","부가세","부가세 포함 합계","지급상태","메모","비용 상태","등록일","등록자","등록 방식","Batch 파일명"] as const;
const CATEGORIES=["외주비","운송비","노무비","설치비","AS 비용","기타 비용"] as const;
const BORDER={style:"thin",color:{rgb:"D8DEE9"}} as const; const FONT="맑은 고딕";
function formatDate(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
function localDate(value:string|null){if(!value)return "";const[y,m,d]=value.slice(0,10).split("-").map(Number);return y&&m&&d?new Date(y,m-1,d):"";}
export function getProjectCostExportFileName(date:Date){return `프로젝트_비용내역_${formatDate(date)}.xlsx`;}
function styleDetail(sheet:Sheet,rowCount:number){sheet["!merges"]=[0,1,2].map(r=>({s:{r,c:0},e:{r,c:HEADERS.length-1}}));sheet["!autofilter"]={ref:`A4:V${Math.max(rowCount+4,4)}`};sheet["!freeze"]={xSplit:0,ySplit:4};sheet["!cols"]=[8,16,28,20,14,14,14,30,14,14,22,18,16,14,17,14,40,12,18,14,16,28].map(wch=>({wch}));sheet["!rows"]=[{hpt:28},{hpt:20},{hpt:20},{hpt:24},...Array.from({length:rowCount},()=>({hpt:22}))];const range=XLSX.utils.decode_range(sheet["!ref"]??"A1:A4");for(let r=0;r<=range.e.r;r++)for(let c=0;c<=range.e.c;c++){const address=XLSX.utils.encode_cell({r,c});const cell=sheet[address]??(sheet[address]={t:"s",v:""});cell.s={font:{name:FONT,sz:10,color:{rgb:"334155"}},alignment:{vertical:"center",horizontal:c===0?"center":"left"}};if(r===0)cell.s={fill:{fgColor:{rgb:"0F172A"}},font:{name:FONT,sz:16,bold:true,color:{rgb:"FFFFFF"}},alignment:{vertical:"center",horizontal:"left"}};else if(r===1||r===2)cell.s={fill:{fgColor:{rgb:"F8FAFC"}},font:{name:FONT,sz:9,color:{rgb:"64748B"}},alignment:{vertical:"center",horizontal:"left"}};else if(r===3)cell.s={fill:{fgColor:{rgb:"1E3A5F"}},font:{name:FONT,sz:10,bold:true,color:{rgb:"FFFFFF"}},alignment:{vertical:"center",horizontal:"center",wrapText:true},border:{top:BORDER,bottom:BORDER,left:BORDER,right:BORDER}};else{cell.s.border={top:BORDER,bottom:BORDER,left:BORDER,right:BORDER};if(c===2||c===7||c===16)cell.s.alignment={vertical:"center",horizontal:"left",wrapText:true};if(c===8||c===9)cell.z="yyyy-mm-dd";if(c===18)cell.z="yyyy-mm-dd hh:mm";if(c>=12&&c<=14)cell.z="#,##0";}}}
export function buildProjectCostExportWorkbook(options:ProjectCostExportOptions){const details:Array<Array<string|number|Date>>=[["프로젝트 비용 내역"],[`다운로드 기준일: ${formatDate(options.generatedAt)}`],[`적용 필터: ${options.filterSummary||"전체"}`],[...HEADERS],...options.rows.map((row,index)=>[index+1,row.project_code??"",row.project_name,row.client_name??"",row.salesperson??"",row.task_manager??"",row.category_name,row.cost_title,localDate(row.cost_date),localDate(row.recognition_date),row.vendor_name??"",row.document_number??"",row.supply_amount_krw,row.vat_amount_krw,row.total_amount_krw,PAYMENT_STATUS_LABEL[row.payment_status],row.memo??"",row.status==="confirmed"?"유효":"무효",new Date(row.created_at),row.created_by_name,row.registration_method,row.batch_file_name??""])];const detailSheet=XLSX.utils.aoa_to_sheet(details,{cellDates:true}) as Sheet;styleDetail(detailSheet,options.rows.length);
  const confirmed=options.rows.filter(row=>row.status==="confirmed");const totals=confirmed.reduce((sum,row)=>({supply:sum.supply+row.supply_amount_krw,vat:sum.vat+row.vat_amount_krw,total:sum.total+row.total_amount_krw}),{supply:0,vat:0,total:0});const categoryTotals=new Map<string,number>(CATEGORIES.map(name=>[name,0]));confirmed.forEach(row=>categoryTotals.set(row.category_name,(categoryTotals.get(row.category_name)??0)+row.supply_amount_krw));const projects=new Map<string,{code:string;name:string;categories:Map<string,number>;total:number}>();confirmed.forEach(row=>{const key=`${row.project_code??""}|${row.project_name}`;const current=projects.get(key)??{code:row.project_code??"",name:row.project_name,categories:new Map<string,number>(CATEGORIES.map(name=>[name,0])),total:0};current.categories.set(row.category_name,(current.categories.get(row.category_name)??0)+row.supply_amount_krw);current.total+=row.supply_amount_krw;projects.set(key,current);});
  const summaryRows:Array<Array<string|number>>=[["프로젝트 비용 요약"],[`적용 필터: ${options.filterSummary||"전체"}`],[],["구분","값"],["전체 비용 행",options.rows.length],["유효 비용",confirmed.length],["무효 비용",options.rows.length-confirmed.length],["총 공급가액",totals.supply],["총 부가세",totals.vat],["총 합계",totals.total],[],["비용 분류","유효 공급가액"],...CATEGORIES.map(name=>[name,categoryTotals.get(name)??0]),[],["프로젝트 코드","프로젝트명",...CATEGORIES,"총 공급가액"],...Array.from(projects.values()).map(project=>[project.code,project.name,...CATEGORIES.map(name=>project.categories.get(name)??0),project.total])];const summary=XLSX.utils.aoa_to_sheet(summaryRows) as Sheet;summary["!freeze"]={xSplit:0,ySplit:4};summary["!cols"]=[18,28,16,16,16,16,16,16,18].map(wch=>({wch}));const range=XLSX.utils.decode_range(summary["!ref"]??"A1:A1");for(let r=0;r<=range.e.r;r++)for(let c=0;c<=range.e.c;c++){const address=XLSX.utils.encode_cell({r,c});const cell=summary[address]??(summary[address]={t:"s",v:""});cell.s={font:{name:FONT,sz:10,color:{rgb:"334155"}},alignment:{vertical:"center",horizontal:c===0?"left":"right"}};if(r===0)cell.s={fill:{fgColor:{rgb:"0F172A"}},font:{name:FONT,sz:16,bold:true,color:{rgb:"FFFFFF"}}};if(r===3||r===11||r===19)cell.s={fill:{fgColor:{rgb:"1E3A5F"}},font:{name:FONT,sz:10,bold:true,color:{rgb:"FFFFFF"}},alignment:{vertical:"center",horizontal:"center"},border:{top:BORDER,bottom:BORDER,left:BORDER,right:BORDER}};if(typeof cell.v==="number")cell.z="#,##0";}
  const workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,detailSheet,"비용 내역");XLSX.utils.book_append_sheet(workbook,summary,"요약");return workbook;}
export function downloadProjectCostExport(options:ProjectCostExportOptions){XLSX.writeFile(buildProjectCostExportWorkbook(options),getProjectCostExportFileName(options.generatedAt),{compression:true});}
