import assert from "node:assert/strict";
import test from "node:test";
import XLSX from "xlsx-js-style";
import {buildProjectCostExportWorkbook,getProjectCostExportFileName,type ProjectCostExportRow} from "./project-cost-export.ts";
function row(index:number,overrides:Partial<ProjectCostExportRow>={}):ProjectCostExportRow{return{project_code:`P-${index%3}`,project_name:`한글 프로젝트 ${index%3}`,client_name:"발주처",salesperson:"김영업",task_manager:"박공무",category_name:index%2?"설치비":"외주비",cost_title:`비용 =${index}`,cost_date:"2026-08-21",recognition_date:index%2?null:"2026-08-22",vendor_name:"업체 +특수",document_number:`INV-${index}`,supply_amount_krw:1000,vat_amount_krw:index===0?0:100,total_amount_krw:index===0?1000:1100,payment_status:"unpaid",memo:"한글 메모\n두 번째 줄",status:"confirmed",created_at:"2026-08-21T10:30:00+09:00",created_by_name:"홍길동",registration_method:index%2?"Excel 일괄등록":"수기 등록",batch_file_name:index%2?"비용.xlsx":null,...overrides};}
function reopen(rows:ProjectCostExportRow[]){const workbook=buildProjectCostExportWorkbook({rows,filterSummary:"비용 분류: 설치비 · 검색: 청라",generatedAt:new Date(2026,7,21)});return XLSX.read(XLSX.write(workbook,{type:"buffer",bookType:"xlsx"}),{type:"buffer",cellDates:true,cellNF:true});}
test("1, 100, 500, 5000건을 직렬화 후 같은 순서로 재열기한다",()=>{for(const count of [1,100,500,5000]){const sheet=reopen(Array.from({length:count},(_,index)=>row(index))).Sheets["비용 내역"];assert.equal(sheet.A5.v,1);assert.equal(sheet[`H${count+4}`].v,`비용 =${count-1}`);}});
test("한글 Label, 날짜, 금액, VAT 0, 메모, 상태와 등록 방식을 출력한다",()=>{const sheet=reopen([row(0),row(1)]).Sheets["비용 내역"];assert.equal(sheet.G5.v,"외주비");assert.equal(sheet.P5.v,"미지급");assert.equal(sheet.N5.v,0);assert.equal(sheet.N5.z,"#,##0");assert.equal(sheet.Q5.v,"한글 메모\n두 번째 줄");assert.equal(sheet.R5.v,"유효");assert.equal(sheet.U5.v,"수기 등록");assert.equal(sheet.U6.v,"Excel 일괄등록");assert.equal(sheet.V6.v,"비용.xlsx");assert.equal(sheet.I5.z,"yyyy-mm-dd");assert.match(String(sheet.A3.v),/설치비/);});
test("요약은 무효 비용을 건수에만 포함하고 유효 비용 금액과 분류·프로젝트별 합계를 집계한다",()=>{const workbook=reopen([row(0),row(1),row(2,{status:"void",supply_amount_krw:9000,vat_amount_krw:900,total_amount_krw:9900})]);const summary=workbook.Sheets["요약"];assert.equal(summary.B5.v,3);assert.equal(summary.B6.v,2);assert.equal(summary.B7.v,1);assert.equal(summary.B8.v,2000);assert.equal(summary.B9.v,100);assert.equal(summary.B10.v,2100);assert.equal(summary.B13.v,1000);assert.equal(summary.B16.v,1000);assert.equal(summary.I21.v,1000);assert.equal(JSON.stringify(workbook).includes("import_batch_id"),false);assert.equal(JSON.stringify(workbook).includes("created_by"),false);});
test("Sheet와 파일명을 고정한다",()=>{assert.deepEqual(reopen([row(0)]).SheetNames,["비용 내역","요약"]);assert.equal(getProjectCostExportFileName(new Date(2026,7,21)),"프로젝트_비용내역_2026-08-21.xlsx");});
